const $=id=>document.getElementById(id);const fmt=n=>'$ '+Math.floor(Number(n||0)).toLocaleString('zh-TW');let currentCat='care';
function daysRatio(dateStr){if(!dateStr)return 1;const d=new Date(dateStr+'T00:00:00');if(isNaN(d))return 1;const y=d.getFullYear(),m=d.getMonth();const days=new Date(y,m+1,0).getDate();return (days-d.getDate()+1)/days}
function init(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.target).classList.add('active')});for(let l=2;l<=8;l++){['qLevel','feeCms'].forEach(id=>$(id).add(new Option('CMS '+l,l)))}Object.entries(TRANSPORT_QUOTA).forEach(([k,v])=>$('qTransport').add(new Option(`${TRANSPORT_LABELS[k]}｜${v.toLocaleString()}元/月`,k)));['qLevel','qDate','qForeign','qTransport'].forEach(id=>$(id).addEventListener('change',calcQuota));calcQuota();document.querySelectorAll('.subtab[data-cat="assist"]').forEach(b=>b.remove());document.querySelectorAll('.subtab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.subtab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentCat=b.dataset.cat;renderServices()});$('serviceSearch').addEventListener('input',renderServices);renderServices();$('addFeeRow').onclick=addFeeRow;addFeeRow();['feeCms','feeIdentity'].forEach(id=>$(id).addEventListener('change',calcFee));buildAtlas();buildPlanChecks();$('genCarePlan').onclick=genCarePlan;buildPhoneChecks();$('genPhone').onclick=genPhone;$('addCulture').onclick=addCultureRow;$('checkRenewal').onclick=checkRenewal;addCultureRow()}
function calcQuota(){const lv=+$('qLevel').value||2,ratio=daysRatio($('qDate').value),foreign=$('qForeign').value==='yes';const base=QUOTA_LEVELS[lv];const careMonthly=foreign?Math.floor(base*.3):base;const care=Math.floor(careMonthly*ratio);const tq=TRANSPORT_QUOTA[$('qTransport').value];const trans=Math.floor(tq*ratio);const respite=lv>=7?RESPITE_QUOTA.high:RESPITE_QUOTA.low;const short=lv>=7?SHORT_STAY_QUOTA.high:SHORT_STAY_QUOTA.low;let cards=[['照顧及專業服務',care,foreign?`原額度 ${fmt(base)}；外看可用30%為 ${fmt(careMonthly)}；再依首月比例計算`:`原額度 ${fmt(base)}；依首月比例計算`],['交通接送',trans,`${TRANSPORT_LABELS[$('qTransport').value]}月額度 ${fmt(tq)}；依開案日期比例計算`],['輔具及居家無障礙｜第一組',40000,'三年額度'],['輔具及居家無障礙｜第二組/科技輔具',60000,'115/7/1起三年額度；第一組與第二組擇一申請'],['喘息服務',respite,'一年額度']];if(foreign)cards.push(['外看短照服務',short,'聘有外籍家庭看護工者適用']);$('quotaOut').innerHTML=cards.map(c=>`<div class="qcard"><span>${c[0]}</span><b>${fmt(c[1])}</b><small>${c[2]}</small></div>`).join('')}
function basePrice(s){return Number(s.price??s.buy??s.rent??0)}
function copayRate(s,identity,region='r2'){if(s.cat==='aa'||s.free)return 0;if(s.cat==='transport'){let r=COPAY.transport[identity];return typeof r==='object'?r[region]:r||0}if(s.cat==='assist')return 1-(COPAY.assist[identity]??0);return (COPAY[s.cat]||COPAY.care)[identity]||0}
function assistGrant(s,identity){const amount=basePrice(s);if(!amount||s.free)return amount;return Math.floor(amount*(COPAY.assist[identity]??0))}
function renderServices(){const q=($('serviceSearch').value||'').toLowerCase().trim();let list=SERVICES.filter(s=>{if(s.cat==='assist')return false;if(currentCat==='care')return s.cat==='care'||s.cat==='respite';if(currentCat==='transport')return s.cat==='transport';if(currentCat==='aa')return s.cat==='aa';return false});if(q)list=list.filter(s=>(s.code+s.name+(s.official||'')+(s.plain||'')+(s.note||'')).toLowerCase().includes(q));$('serviceList').innerHTML=list.map(s=>cardHtml(s)).join('')||'<div class="panel">查無資料</div>'}
function cardHtml(s){let amount=s.price!=null?`${fmt(s.price)}${s.remote?`／原離島 ${fmt(s.remote)}`:''}`:s.buy||s.rent?`${s.buy?`購置補助上限 ${fmt(s.buy)}`:''}${s.buy&&s.rent?'｜':''}${s.rent?`租賃補助上限 ${fmt(s.rent)}`:''}`:'依地方主管機關或特約單位公告';let meta=ASSIST_ATLAS_META?.[s.code]||{};let img=(meta.img||s.img)?`<img class="aid-img" loading="lazy" src="assets/assistive/${meta.img||s.img}" alt="${s.name}">`:'';let pills='';if(s.cat==='aa')pills='<span class="pill good">政府獎勵金</span><span class="pill good">免部分負擔</span><span class="pill good">不扣長照額度</span>';else if(s.cat==='assist'){if(s.free)pills='<span class="pill good">免部分負擔</span>';else pills=`<span class="pill">第一類 ${fmt(assistGrant(s,'first'))}</span><span class="pill">第二類 ${fmt(assistGrant(s,'second'))}</span><span class="pill">第三類 ${fmt(assistGrant(s,'third'))}</span>`}else if(s.cat==='transport')pills='<span class="pill warn">支付價格由地方公告</span><span class="pill">第一類 0%</span><span class="pill">第二類依區域9%左右</span><span class="pill">第三類依區域27%左右</span>';else pills=`<span class="pill">第一類 ${fmt(0)}</span><span class="pill">第二類 ${fmt(basePrice(s)*copayRate(s,'second'))}</span><span class="pill">第三類 ${fmt(basePrice(s)*copayRate(s,'third'))}</span>`;return `<article class="svc">${img}<h3>${s.code} ${s.name}</h3><p><b>${s.cat==='assist'?'補助金額':'支付金額'}：</b>${amount}</p><div class="price">${pills}</div><div class="official"><b>支付基準說明</b>\n${s.official||'依支付基準及地方主管機關公告辦理。'}</div><p><b>個管翻譯機：</b>${s.plain||'依個案實際需求與支付基準評估。'}</p><p class="hint"><b>注意事項：</b>${s.note||'請依個案需求、照顧計畫及最新規定辦理。'}</p></article>`}

let currentAtlas='all';
function assistGroup(code){return (ASSIST_ATLAS_META[code]||{}).group||(/FA/.test(code)?'home':/^EA/.test(code)?'bath':/^E[BC]/.test(code)?'mobility':/^E[DG H]/.test(code)?'bedmove':'life')}
function buildAtlas(){if(!$('atlasList'))return;document.querySelectorAll('.atlas-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.atlas-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentAtlas=b.dataset.atlas;renderAtlas()});$('atlasSearch').oninput=renderAtlas;renderAtlas()}
function atlasHasImage(a){const m=ASSIST_ATLAS_META[a.code]||{};const imgs=m.imgs||(m.img?[m.img]:(a.img?[a.img]:[]));return imgs.length>0}
function renderAtlas(){const q=($('atlasSearch')?.value||'').toLowerCase().trim();let list=ASSIST.filter(a=>currentAtlas==='all'||assistGroup(a.code)===currentAtlas);if(q)list=list.filter(a=>{const m=ASSIST_ATLAS_META[a.code]||{};return (a.code+a.name+(a.official||'')+(a.plain||'')+(m.targets||[]).join('')+(m.features||[]).join('')).toLowerCase().includes(q)});$('atlasList').innerHTML=list.map(a=>atlasCard(a)).join('')||'<div class="panel">查無資料</div>'}
function atlasCard(a){
  const m=ASSIST_ATLAS_META[a.code]||{};
  const imgs=m.imgs||(m.img?[m.img]:(a.img?[a.img]:[]));
  const amountParts=[];
  if(a.buy) amountParts.push(`購置補助上限 ${fmt(a.buy)}`);
  if(a.rent) amountParts.push(`租賃補助上限 ${fmt(a.rent)}${a.buy?'／月':'／月'}`);
  const amount=amountParts.length?amountParts.join('｜'):'依公告或備查';
  const subsidyTable=renderAssistSubsidyTable(a);
  const targets=(m.targets&&m.targets.length?m.targets:['依輔具評估結果及支付基準規定辦理']).map(x=>`<li>${x}</li>`).join('');
  const features=(m.features&&m.features.length?m.features:extractRecognized(a)).map(x=>`<li>${x}</li>`).join('');
  const imgHtml=imgs.length?`<div class="atlas-img-wrap ${imgs.length>1?'multi':''}">${imgs.map(img=>`<img loading="lazy" src="assets/assistive/${img}" alt="${a.name}">`).join('')}</div>`:'';
  return `<article class="atlas-card">${imgHtml}<div class="atlas-body"><h3><span>${a.code}</span>${a.name}</h3><p class="subsidy"><b>${amount}</b></p>${subsidyTable}<div class="atlas-cols"><div><b>建議使用狀況</b><ul>${targets}</ul></div><div><b>附加功能／支付基準認列內容</b><ul>${features}</ul></div></div><details open><summary>支付基準說明</summary><p>${a.official||'依支付基準及地方主管機關公告辦理。'}</p></details></div></article>`
}
function renderAssistSubsidyTable(a){
  const rows=[];
  const addRows=(label,amount)=>{
    if(!amount){rows.push(`<tr><td>${label}</td><td colspan="3">依公告或備查</td></tr>`);return;}
    if(a.free){rows.push(`<tr><td>${label}</td><td>${fmt(amount)}</td><td>${fmt(amount)}</td><td>${fmt(amount)}</td></tr>`);}
    else{rows.push(`<tr><td>${label}</td><td>${fmt(amount)}</td><td>${fmt(Math.floor(amount*.9))}</td><td>${fmt(Math.floor(amount*.7))}</td></tr>`);}
  };
  if(a.buy) addRows('購置',a.buy);
  if(a.rent) addRows('租賃/月',a.rent);
  if(!a.buy&&!a.rent) rows.push(`<tr><td>補助</td><td colspan="3">依地方主管機關公告或特約單位備查</td></tr>`);
  const note=a.free?`<div class="mini-note">本項依支付基準免部分負擔，表列為補助上限。</div>`:`<div class="mini-note">輔具及居家無障礙補助：第一類100%、第二類90%、第三類70%。實際補助仍依核定及地方規定。</div>`;
  return `<div class="assist-table-wrap"><table class="assist-subsidy"><thead><tr><th>項目</th><th>第一類</th><th>第二類</th><th>第三類</th></tr></thead><tbody>${rows.join('')}</tbody></table>${note}</div>`;
}
function extractRecognized(a){let t=(a.official||'').replace(/。/g,'。|').split('|').filter(Boolean);return t.length?t.slice(0,4):['依支付基準認列項目']}

function addFeeRow(defaultCode='BA07',defaultTimes=1){const row=document.createElement('div');row.className='fee-row';const opts=SERVICES.filter(s=>['care','respite'].includes(s.cat)&&Number(s.price)>0).map(s=>`<option value="${s.code}">${s.code}｜${s.name}｜${s.price}元</option>`).join('');row.innerHTML=`<label>碼別<select class="feeCode">${opts}</select></label><label>每月次數<input class="feeTimes" type="number" min="0" value="${defaultTimes}" inputmode="numeric"></label><button type="button" class="remove">刪除</button>`;$('feeRows').appendChild(row);const codeEl=row.querySelector('.feeCode');if([...codeEl.options].some(o=>o.value===defaultCode))codeEl.value=defaultCode;row.querySelector('.remove').onclick=()=>{row.remove();calcFee()};row.querySelectorAll('select,input').forEach(el=>['input','change','keyup','blur','click'].forEach(evt=>el.addEventListener(evt,calcFee)));setTimeout(calcFee,0)}
function calcFee(){const lv=+$('feeCms')?.value||2,identity=$('feeIdentity')?.value||'third',quota=QUOTA_LEVELS[lv]||0;let planned=0,self=0,over=0,remain=quota;document.querySelectorAll('#feeRows .fee-row').forEach(r=>{const code=r.querySelector('.feeCode')?.value;const s=SERVICES.find(x=>x.code===code);const unit=Number(s?.price||0);const raw=r.querySelector('.feeTimes')?.value;const times=Math.max(0,Math.floor(Number(raw||0)));if(!s||!unit||!times)return;planned+=unit*times;const payableTimes=Math.min(times,Math.floor(remain/unit));if(payableTimes>0){remain-=unit*payableTimes;self+=Math.floor(unit*copayRate(s,identity))*payableTimes}const overTimes=times-payableTimes;if(overTimes>0)over+=unit*overTimes;});const set=(id,val)=>{const el=$(id);if(el)el.textContent=fmt(val)};set('feeTotal',planned);set('feeQuota',quota);set('feeSelfPay',self);set('feeOverage',over);set('feeClientTotal',self+over);set('feeRemain',remain);const note=$('feeNotice');if(note){note.className='notice '+(over?'danger':'success');note.textContent=over?`已超出 CMS 額度，超額自費 ${fmt(over)}。剩餘額度不足以支應一支服務時，該支服務全額自費。`:`目前尚未超出 CMS 額度，剩餘額度 ${fmt(remain)}。`;}}
function groupHtml(title,key){return `<details open><summary>${title}</summary><div class="checkbox-grid">${PLAN_OPTIONS[key].map(v=>`<label class="check"><input type="checkbox" value="${v}">${v}</label>`).join('')}<label class="check">其他：<input type="text" data-other="${key}" placeholder="自行補充"></label></div></details>`}
function buildPlanChecks(){$('cpChecks').innerHTML=groupHtml('疾病/特殊狀況','diseases')+groupHtml('認知情緒','cognition')+groupHtml('行動移位','mobility')+groupHtml('進食營養','eating')+groupHtml('排泄照護','toileting');$('cpFamily').innerHTML=groupHtml('家庭與照顧者','family');$('cpEnv').innerHTML=groupHtml('環境與現有輔具','env');$('cpProblems').innerHTML=groupHtml('照顧問題','problems')}
function vals(container){const c=$(container);let a=Array.from(c.querySelectorAll('input[type=checkbox]:checked')).map(x=>x.value);Array.from(c.querySelectorAll('[data-other]')).forEach(x=>{if(x.value.trim())a.push(x.value.trim())});return a}
function genCarePlan(){const d=$('cpDate').value||'____年__月__日',t=$('cpTime').value||'__：__';const health=vals('cpChecks').join('、');const fam=vals('cpFamily').join('、');const env=vals('cpEnv').join('、');const probs=vals('cpProblems');const ptxt=(probs.length?probs:['請依問題清單排序前5項補充']).map((p,i)=>`${i+1}.${p}：${p==='請依問題清單排序前5項補充'?'':p+'相關需求需持續評估與服務介入。'}`).join('\n');$('careplanOut').value=`${$('cpName').value||'個案'}\n一、本案於${d}${t}進行家訪，與${$('cpPeople').value||'個案及家屬'}討論照顧計畫。\n\n二、個案摘述\n1.個案狀況：${health||'請選擇個案狀況'}。${$('cpHealthNote').value}\n2.家庭狀況：${fam||'請選擇家庭支持與照顧者狀況'}。${$('cpFamilyNote').value}\n3.居住環境：${env||'請選擇環境與輔具狀況'}。${$('cpEnvNote').value}\n\n三、照顧問題\n${ptxt}\n\n四、照顧目標\n1.短期目標(1個月)：${$('cpGoalS').value||'依個案主要照顧問題，於1個月內穩定服務銜接並降低立即風險。'}\n2.中期目標(3個月)：${$('cpGoalM').value||'持續追蹤服務使用情形，依個案狀況調整照顧計畫。'}\n3.長期目標(6個月)：${$('cpGoalL').value||'維持個案於熟悉居家環境中安全生活，並降低主要照顧者負荷。'}\n\n五、照顧計畫\n1.照顧及專業服務：${$('cpCare').value||'暫無或待補充。'}\n2.交通接送：${$('cpTransport').value||'暫無或待補充。'}\n3.輔具及居家無障礙環境改善：${$('cpAssist').value||'暫無或待補充。'}\n4.喘息服務/短照服務：${$('cpRespite').value||'暫無或待補充。'}\n5.轉介其他資源：${$('cpResource').value||'暫無或待補充。'}\n\n六、擬定計畫和實際使用服務的落差\n${$('cpGap').value||'無。'}`}
function buildPhoneChecks(){const map={body:'個案體況追蹤',cognition:'認知情緒',services:'服務使用狀況',professional:'專業服務追蹤',caregiver:'照顧者狀況',safety:'安全風險',resources:'資源需求'};$('phoneChecks').innerHTML=Object.entries(map).map(([k,t])=>`<details open><summary>${t}</summary><div class="checkbox-grid">${(PHONE_OPTIONS[k]||[]).map(v=>`<label class="check"><input type="checkbox" value="${v.id}" data-phone="${k}">${v.label}</label>`).join('')}</div></details>`).join('')}
function phoneSelectedByGroup(){const picked={};document.querySelectorAll('[data-phone]:checked').forEach(x=>{const item=(PHONE_OPTIONS[x.dataset.phone]||[]).find(v=>v.id===x.value);if(item){(picked[x.dataset.phone]||(picked[x.dataset.phone]=[])).push(item)}});return picked}
function joinTexts(items){return (items||[]).map(x=>x.text).join('')}
function makePara(parts){return parts.filter(Boolean).map(x=>String(x).trim()).filter(Boolean).join('')}
function genPhone(){const picked=phoneSelectedByGroup();const bodyNote=$('phBodyNote').value.trim();const serviceNote=$('phServiceNote').value.trim();const satisNote=$('phSatisNote').value.trim();const method=$('phMethod').value||'電話';const person=$('phPerson').value||'案家';const style=$('phStyle')?.value||'normal';
  const body=makePara([joinTexts(picked.body),joinTexts(picked.cognition),bodyNote]);
  const service=makePara([joinTexts(picked.services),joinTexts(picked.professional),serviceNote]);
  const caregiver=makePara([joinTexts(picked.caregiver)]);
  const safety=makePara([joinTexts(picked.safety)]);
  const resource=makePara([joinTexts(picked.resources),satisNote]);
  let paras=[];
  if(style==='short'){
    paras.push(makePara([`本次以${method}聯繫${person}進行追蹤。`,body||'案家表示個案目前體況尚稱穩定，暫無明顯異常情形。',service||'目前長照服務依照顧計畫持續提供。']));
    paras.push(makePara([caregiver,safety,resource||'案家表示目前暫無新增資源需求，後續將持續追蹤個案狀況及服務使用情形。']));
  }else{
    paras.push(makePara([`本次以${method}聯繫${person}進行電訪追蹤。`,body||'案家表示個案近期體況尚稱穩定，精神及日常生活狀況無明顯異常，後續仍需持續觀察。']));
    paras.push(makePara([service||'目前長照服務均依照顧計畫持續提供，服務使用情形尚稱穩定，案家暫無反映需立即調整之事項。']));
    if(caregiver)paras.push(caregiver);
    if(safety)paras.push(safety);
    paras.push(makePara([resource||'案家表示目前暫無新增資源需求，後續將持續追蹤個案體況、服務使用情形及照顧需求變化。']));
    if(style==='full'){
      paras.push('本次電訪已同步提醒案家，如個案體況、家庭照顧安排或服務需求有明顯變化，得主動聯繫個案管理單位，後續將依實際需求協助評估照顧計畫調整或相關資源連結。');
    }
  }
  const follow=style==='short'?'持續追蹤個案狀況及服務使用情形，必要時協助調整照顧計畫或連結相關資源。':'後續將持續追蹤個案身心狀況、家庭支持情形、服務使用情形及照顧需求變化，必要時協助辦理照顧計畫調整或連結相關資源。';
  $('phoneOut').value=`一、電訪日期：${$('phDate').value||'____年__月__日'}
二、電訪時間：${$('phTime').value||'__：__'}
三、電訪方式：${method}
四、電訪對象：${person}

五、電訪摘要：

${paras.filter(Boolean).map(p=>'　　'+p).join('\n\n')}

六、後續處理：
　　${follow}`
}
function addCultureRow(){const div=document.createElement('div');div.className='fee-row';div.innerHTML=`<label>課程日期<input type="date" class="cDate"></label><label>課程類別<select class="cType"><option value="old">舊制/多元文化族群</option><option value="indigenous">原住民族文化安全</option><option value="multi">多元族群文化敏感度</option></select></label><label>點數<input type="number" step="0.5" class="cPoint" value="1"></label><button type="button" class="remove">刪除</button>`;$('cultureRows').appendChild(div);div.querySelector('.remove').onclick=()=>div.remove()}
function checkRenewal(){const total=+$('renewTotal').value||0,online=+$('renewOnline').value||0,q=+$('rq').value||0,e=+$('re').value||0,l=+$('rl').value||0,safe=+$('rsafe').value||0;const start=new Date($('renewStart').value),end=new Date($('renewEnd').value);let issues=[],ok=[];if(total>=120)ok.push('六年總積分已達120點。');else issues.push(`六年總積分尚缺 ${120-total} 點。`);if(q+e+l>=24&&q>0&&e>0&&l>0)ok.push('專業品質/倫理/法規合計達24點且各項不為0。');else issues.push('專業品質、倫理、法規需合計至少24點且各項不得為0。');if(safe>=10)ok.push('消防/緊急/感染/性別合計達10點。');else issues.push('消防安全、緊急應變、感染管制、性別敏感度合計需至少10點。');if(end>=new Date('2026-07-01')&&online>80)issues.push('115/07/01起網路課程最高採認80點，超過部分可能不採計。');const courses=Array.from(document.querySelectorAll('#cultureRows .fee-row')).map(r=>({d:new Date(r.querySelector('.cDate').value),type:r.querySelector('.cType').value,p:+r.querySelector('.cPoint').value||0})).filter(x=>!isNaN(x.d));const split=new Date('2024-06-03');const oldPts=courses.filter(c=>c.d<split&&c.type==='old').reduce((a,c)=>a+c.p,0);if(start<split){if(oldPts>=2)ok.push('113/06/02以前舊制/多元文化族群課程已達2點。');else issues.push('113/06/02以前僅採舊制/多元文化族群課程，尚未達2點。')}let ylines=[];if(end>=split){let yStart=new Date(Math.max(start.getTime(),split.getTime())),idx=1;while(yStart<end){let yEnd=new Date(yStart);yEnd.setFullYear(yEnd.getFullYear()+1);if(yEnd>end)yEnd=new Date(end);let ind=courses.filter(c=>c.d>=yStart&&c.d<yEnd&&c.type==='indigenous').reduce((a,c)=>a+c.p,0);let mul=courses.filter(c=>c.d>=yStart&&c.d<yEnd&&c.type==='multi').reduce((a,c)=>a+c.p,0);let pass=ind>=1&&mul>=1;ylines.push(`${pass?'✅':'❌'}第${idx}年度：原民${ind}點／多元${mul}點`);if(!pass)issues.push(`第${idx}年度原民/多元課程未完成。`);yStart=yEnd;idx++}}let can=new Date(end);can.setMonth(can.getMonth()-6);let after=new Date(end);after.setDate(after.getDate()+1);$('renewalOut').value=`檢核結果：${issues.length?'尚未完全符合':'初步符合'}\n\n已符合：\n${ok.join('\n')||'無'}\n\n待補事項：\n${issues.join('\n')||'無'}\n\n原民/多元年度檢核：\n${ylines.join('\n')||'無需年度檢核或未輸入日期'}\n\n${issues.some(x=>x.includes('原民')||x.includes('多元'))?`最快換證時間：到期後隔天（${after.toLocaleDateString('zh-TW')}）且補足學分後辦理。`:`最早可於到期日前6個月申請（${can.toLocaleDateString('zh-TW')}）。`}`}
function copyText(id){const el=$(id);el.select();document.execCommand('copy')}
window.addEventListener('DOMContentLoaded',init);
