const $ = id => document.getElementById(id);
const today = () => new Date().toISOString().slice(0,10);
function toast(msg){const old=document.querySelector('.copy-toast'); if(old) old.remove(); const t=document.createElement('div'); t.className='copy-toast'; t.textContent=msg; document.body.appendChild(t); setTimeout(()=>t.remove(),1700)}
async function copyFrom(id,label='內容'){const el=$(id); if(!el) return; if(!el.value && el.textContent) el.value=el.textContent; try{await navigator.clipboard.writeText(el.value || el.textContent); toast(`已複製${label}`)}catch(e){el.focus?.(); el.select?.(); document.execCommand('copy'); toast(`已複製${label}`)}}
function roc(dateStr){ if(!dateStr) return '○年○月○日'; const [y,m,d]=dateStr.split('-').map(Number); return y?`${y-1911}年${m}月${d}日`:dateStr; }
function fillLevels(){ const opts=Object.keys(cmsLevels).map(l=>`<option value="${l}">第${l}級｜${money(cmsLevels[l])}元/月</option>`).join(''); ['quotaLevel','planLevel'].forEach(id=>{if($(id)) $(id).innerHTML=opts}); }
function initTabs(){document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tool').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$(btn.dataset.target)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}));}

function daysInMonth(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function firstMonthAmount(amount,dateStr){ if(!dateStr) return amount; const d=new Date(dateStr+'T00:00:00'); if(isNaN(d)) return amount; const total=daysInMonth(d); const remain=total-d.getDate()+1; return Math.floor(amount*remain/total); }
function initQuota(){ $('openDate').value=today(); ['quotaLevel','openDate','foreignWorker'].forEach(id=>$(id)?.addEventListener('input',calcQuota)); calcQuota(); }
function calcQuota(){ const level=$('quotaLevel').value||2; const open=$('openDate').value; const foreign=$('foreignWorker').value==='yes'; const base=cmsLevels[level]; const careBase=foreign?Math.floor(base*0.3):base; const careFirst=firstMonthAmount(careBase,open); const transportFirst=Object.fromEntries(Object.entries(transportLimits).map(([k,v])=>[k,firstMonthAmount(v,open)])); const respite=respiteLimits(level); const short=shortStayForeignLimits(level); const result=$('quotaResult'); result.innerHTML=`
  <div class="quota-card card ${foreign?'foreign':''}"><h3>照顧及專業服務</h3><strong>${money(careFirst)}</strong><small>${open?`首月比例：${roc(open)}開案起算。`:''}${foreign?'｜已依外籍看護工規定採照顧及專業服務額度30%。':''}</small></div>
  <div class="quota-card card"><h3>交通接送服務</h3><div class="transport-table">${Object.entries(transportFirst).map(([k,v],i)=>`<div class="transport-cell">${['第一區','第二區','第三區','第四區'][i]}<b>${money(v)}</b></div>`).join('')}</div><small>此處為交通接送月額度之首月比例；單趟支付由地方主管機關公告。</small></div>
  <div class="quota-card card"><h3>輔具及居家無障礙</h3><strong>${money(assistiveLimits.group1)}</strong><small>第一組三年額度；第二組為 ${money(assistiveLimits.group2)} 元／三年，依規定擇一申請。</small></div>
  <div class="quota-card card"><h3>喘息服務</h3><strong>${money(respite)}</strong><small>一年額度：第2至6級 ${money(32340)} 元；第7至8級 ${money(48510)} 元。</small></div>
  ${foreign?`<div class="quota-card card foreign"><h3>外籍看護工家庭短照服務</h3><strong>${money(short)}</strong><small>外看家庭適用：第2至6級 ${money(87780)} 元；第7至8級 ${money(71610)} 元。</small></div>`:''}`; }

let activeGroup='care';
function initCodeTool(){ const tabs=$('codeCategoryTabs'); tabs.innerHTML=codeGroups.map(g=>`<button class="pill ${g.key===activeGroup?'active':''}" data-group="${g.key}">${g.label}</button>`).join(''); tabs.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{activeGroup=b.dataset.group; tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active')); b.classList.add('active'); renderCodes();})); $('codeSearch').addEventListener('input',renderCodes); renderCodes(); }
function selfPayCells(item){ const rate=ratesByType[item.type] || ratesByType.care; if(item.code==='DA01') return `<div class="transport-table"><div class="transport-cell">第一區月額度<b>${money(1680)}</b></div><div class="transport-cell">第二區月額度<b>${money(1840)}</b></div><div class="transport-cell">第三區月額度<b>${money(2000)}</b></div><div class="transport-cell">第四區月額度<b>${money(2400)}</b></div></div><div class="mini-table"><div class="mini-cell"><span>第一類</span><strong>0</strong></div><div class="mini-cell"><span>第二類 9%</span><strong>依實際車資</strong></div><div class="mini-cell"><span>第三類 27%</span><strong>依實際車資</strong></div></div>`;
 const price = item.price ?? item.rent ?? 0; const labelSecond = item.type==='free'?'0%':`${Math.round(rate.second*100)}%`; const labelThird = item.type==='free'?'0%':`${Math.round(rate.third*100)}%`; return `<div class="mini-table"><div class="mini-cell"><span>支付/上限</span><strong>${price?money(price):'依公告'}</strong></div><div class="mini-cell"><span>第二類 ${labelSecond}</span><strong>${price?money(floorMoney(price,rate.second)):'依公告'}</strong></div><div class="mini-cell"><span>第三類 ${labelThird}</span><strong>${price?money(floorMoney(price,rate.third)):'依公告'}</strong></div></div>`; }
function renderCodes(){ const q=($('codeSearch').value||'').trim().toLowerCase(); let list=allCodes.filter(x=>{ if(activeGroup==='care') return ['care','respite','free'].includes(x.type) && x.code!=='DA01'; if(activeGroup==='transport') return x.type==='transport'; if(activeGroup==='assistive') return x.type==='assistive'; }); if(q) list=list.filter(x=>[x.code,x.name,x.category,x.desc,x.note,x.plain].join(' ').toLowerCase().includes(q)); $('codeList').innerHTML=list.map(x=>`<article class="code-card"><h3>${x.code}｜${x.name}</h3><div class="tag-row"><span class="tag">${x.category}</span><span class="tag">${ratesByType[x.type]?.label||''}</span><span class="tag">${x.unit||''}</span></div>${x.img?`<div class="aid-img"><img src="assets/${x.img}.svg" alt="${x.name}示意圖"></div>`:''}${selfPayCells(x)}<p><b>內容摘要：</b>${x.desc}</p><p><b>注意事項：</b>${x.note}</p><div class="plain"><b>個管白話：</b>${x.plain}</div></article>`).join('') || '<div class="card">查無符合項目。</div>'; }

function serviceOptions(){return feeSelectable.map(s=>`<option value="${s.code}">${s.code} ${s.name}</option>`).join('')}
function addFeeRow(code='BA20',qty=1){const div=document.createElement('div'); div.className='fee-row'; div.innerHTML=`<label>碼別<select class="fee-code">${serviceOptions()}</select></label><label>數量<input class="fee-qty" type="number" min="0" step="0.5" value="${qty}"></label><button class="remove" type="button">刪除</button>`; div.querySelector('.fee-code').value=code; div.querySelectorAll('select,input').forEach(el=>el.addEventListener('input',calcFee)); div.querySelector('.remove').addEventListener('click',()=>{div.remove();calcFee()}); $('feeRows').appendChild(div); calcFee();}
function itemAmount(item){ if(item.code==='DA01') return 0; return Number(item.price ?? item.rent ?? 0); }
function calcFee(){ const identity=$('feeIdentity').value; let total=0,self=0; document.querySelectorAll('.fee-row').forEach(row=>{const code=row.querySelector('.fee-code').value; const qty=Number(row.querySelector('.fee-qty').value||0); const item=feeSelectable.find(x=>x.code===code); if(!item) return; const amount=itemAmount(item)*qty; total+=amount; const rate=identity==='first'?0:(ratesByType[item.type]?.[identity]??0); self+=Math.floor(amount*rate);}); $('feePayTotal').textContent=money(total); $('feeSelfTotal').textContent=money(self);}
function initFee(){ $('addFeeRow').addEventListener('click',()=>addFeeRow()); $('feeIdentity').addEventListener('change',calcFee); addFeeRow('BA20',8); }

const problemOptions=['身體清潔需協助','沐浴安全疑慮','進食或營養需追蹤','移位／上下樓困難','居家環境有跌倒風險','主要照顧者負荷','社會參與不足','就醫交通需協助','管路或傷口照護需指導','失智或困擾行為需追蹤'];
function checkItem(label,id,val){return `<label class="check-item"><input type="checkbox" id="${id}" value="${val||label}"><span>${label}</span></label>`}
function initCarePlan(){ $('planDate').value=today(); $('problemChecks').innerHTML=problemOptions.map((x,i)=>checkItem(x,`prob_${i}`)).join(''); $('planServiceChecks').innerHTML=allCodes.filter(x=>['BA','BB','BC','BD','CA','CB','CC','CD','DA','GA'].some(p=>x.code.startsWith(p))).map(x=>checkItem(`${x.code} ${x.name}`,`planSvc_${x.code}`,`${x.code}${x.name}`)).join(''); $('generatePlan').addEventListener('click',generatePlan); $('copyPlan').addEventListener('click',()=>copyFrom('planOutput','照顧計畫')); $('clearPlan').addEventListener('click',()=>document.querySelectorAll('#carePlanTool input,#carePlanTool textarea').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value=''})); }
function checked(container){return Array.from(document.querySelectorAll(`#${container} input:checked`)).map(x=>x.value)}
function generatePlan(){ const probs=checked('problemChecks'); const svcs=checked('planServiceChecks'); const text=`一、訪視日期與參與者\n訪視日期：${roc($('planDate').value)}\n參與者：${$('planPeople').value||'未填寫'}\n個案：${$('planCase').value||'案主'}（CMS第${$('planLevel').value}級）\n\n二、個案摘述\n${$('planSummary').value||'請補充個案疾病、身體功能、生活自理及近期變化。'}\n\n三、主要照顧者與家庭支持\n${$('planCaregiver').value||'請補充主要照顧者、家庭支持與照顧壓力情形。'}\n\n四、主要照顧問題\n${probs.length?probs.map((p,i)=>`${i+1}. ${p}`).join('\n'):'1. 尚未勾選主要照顧問題。'}${$('planProblemNote').value?`\n補充：${$('planProblemNote').value}`:''}\n\n五、計畫目標\n短期目標：協助個案於日常生活中獲得必要照顧支持，降低照顧風險。\n中期目標：維持個案身體功能與居家安全，減輕主要照顧者照顧負荷。\n長期目標：促進個案在熟悉環境中穩定生活，維持生活品質與家庭照顧量能。\n\n六、服務安排\n${svcs.length?svcs.map((s,i)=>`${i+1}. ${s}`).join('\n'):'尚未勾選服務碼別。'}${$('planServiceNote').value?`\n補充：${$('planServiceNote').value}`:''}\n\n七、後續追蹤\n後續將持續追蹤個案體況、服務使用情形、家屬滿意度及照顧需求變化，必要時辦理照顧計畫調整或轉介相關資源。`; $('planOutput').value=text; }

function initRenewal(){ $('addCulture').addEventListener('click',()=>addCultureRow()); $('checkRenewal').addEventListener('click',checkRenewal); $('copyRenewal').addEventListener('click',()=>copyFrom('renewOutput','檢核結果')); $('clearRenewal').addEventListener('click',()=>{document.querySelectorAll('#renewalTool input,#renewalTool textarea').forEach(x=>x.value=''); $('cultureRows').innerHTML=''; $('renewSummary').className='notice'; $('renewSummary').textContent='請輸入資料後檢核。'; $('renewOutput').value='';}); addCultureRow(); }
function addCultureRow(){ const div=document.createElement('div'); div.className='culture-row'; div.innerHTML=`<label>課程日期<input class="cul-date" type="date"></label><label>課程類別<select class="cul-type"><option value="indigenous">原民文化</option><option value="diverse">多元文化</option><option value="old">舊制／多元文化族群</option></select></label><label>點數<input class="cul-point" type="number" step="0.5" min="0" value="1"></label><button class="remove" type="button">刪除</button>`; div.querySelector('.remove').addEventListener('click',()=>div.remove()); $('cultureRows').appendChild(div); }
function num(id){return Number($(id).value||0)}
function checkRenewal(){ const msgs=[]; let ok=true; const total=num('renewTotal'), online=num('renewOnline'); if(total<120){ok=false;msgs.push(`總積分不足120點，目前${total}點。`)} else msgs.push(`總積分已達120點，目前${total}點。`); if(online>80){ok=false;msgs.push(`網路課程超過80點採認上限，目前${online}點。`)} else msgs.push(`網路課程${online}點。`); const q=num('renewQuality'), e=num('renewEthics'), l=num('renewLaw'), qel=q+e+l; if(qel<24||q===0||e===0||l===0){ok=false;msgs.push(`專業品質／倫理／法規未達標：合計${qel}點，且三項皆需有點數。`)} else msgs.push(`專業品質／倫理／法規合計${qel}點，初步符合。`); const four=num('renewFire')+num('renewEmergency')+num('renewInfection')+num('renewGender'); if(four<10||['renewFire','renewEmergency','renewInfection','renewGender'].some(id=>num(id)===0)){ok=false;msgs.push(`消防／緊急／感染／性別未達標：合計${four}點，四項皆需有點數。`)} else msgs.push(`消防／緊急／感染／性別合計${four}點，初步符合。`);
 const cutoff=new Date('2024-06-03T00:00:00'); let oldPts=0, post={}; document.querySelectorAll('.culture-row').forEach(r=>{const d=r.querySelector('.cul-date').value; const type=r.querySelector('.cul-type').value; const p=Number(r.querySelector('.cul-point').value||0); if(!d) return; const dt=new Date(d+'T00:00:00'); if(dt<cutoff){ if(type==='old') oldPts+=p; } else { const y=dt.getFullYear(); post[y]??={indigenous:0,diverse:0}; if(type==='indigenous'||type==='diverse') post[y][type]+=p; }}); if(oldPts>0&&oldPts<2){ok=false;msgs.push(`113/06/02以前舊制／多元文化族群未達2點，目前${oldPts}點。`)} if(oldPts>=2) msgs.push(`113/06/02以前舊制／多元文化族群${oldPts}點，初步符合。`); Object.entries(post).forEach(([y,v])=>{ if(v.indigenous<1||v.diverse<1){ok=false;msgs.push(`${y}年度原民／多元未達標：原民${v.indigenous}點、多元${v.diverse}點。`)} else msgs.push(`${y}年度原民／多元初步符合：原民${v.indigenous}點、多元${v.diverse}點。`);}); if(!Object.keys(post).length && oldPts===0){msgs.push('尚未輸入原民／多元課程資料，請補充後再判斷。');}
 const summary=$('renewSummary'); summary.className='notice '+(ok?'ok':'bad'); summary.textContent=ok?'初步檢核：符合主要條件。':'初步檢核：尚有項目需補足。'; $('renewOutput').value=`長照小卡換證檢核結果\n小卡效期：${roc($('renewStart').value)}至${roc($('renewEnd').value)}\n\n${msgs.map(x=>'・'+x).join('\n')}\n\n提醒：本工具為初步檢核，實際仍請以主管機關、訓練認證系統與最新規定為準。`; }

function initPhone(){ $('phoneDate').value=today(); $('phoneServiceChecks').innerHTML=allCodes.filter(x=>['BA','BB','BC','BD','CA','CB','CC','CD','DA','GA'].some(p=>x.code.startsWith(p))).map(x=>checkItem(`${x.code} ${x.name}`,`phoneSvc_${x.code}`,`${x.code}${x.name}`)).join(''); $('generatePhone').addEventListener('click',generatePhone); $('copyPhone').addEventListener('click',()=>copyFrom('phoneOutput','電訪紀錄')); $('clearPhone').addEventListener('click',()=>document.querySelectorAll('#phoneTool input,#phoneTool textarea').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value=''})); }
function generatePhone(){ const svcs=checked('phoneServiceChecks'); const txt=`電訪紀錄\n日期：${roc($('phoneDate').value)}${$('phoneTime').value?` ${$('phoneTime').value}`:''}\n聯繫方式：${$('phoneMethod').value}\n聯繫對象：${$('phoneTarget').value||'未填寫'}\n\n一、個案體況追蹤\n本次聯繫追蹤個案體況，聯繫對象表示個案目前${$('phoneHealth').value}，${$('phoneMood').value}。${$('phoneHealthNote').value?`補充說明：${$('phoneHealthNote').value}`:'暫無其他特殊體況反映。'}\n\n二、各項服務追蹤\n目前追蹤服務項目：${svcs.length?svcs.join('、'):'未勾選特定服務項目'}。${$('phoneServiceNote').value?`服務使用情形：${$('phoneServiceNote').value}`:'聯繫對象未反映服務執行異常。'}\n\n三、服務滿意度\n聯繫對象表示目前服務滿意度為「${$('phoneSatisfaction').value}」。服務調整需求：${$('phoneAdjust').value}。\n\n四、後續處理\n${$('phoneExtra').value?$('phoneExtra').value:'後續持續追蹤個案體況、各項服務使用情形及家屬滿意度，如有服務需求變化再進行照顧計畫調整。'}`; $('phoneOutput').value=txt; }

window.addEventListener('DOMContentLoaded',()=>{fillLevels();initTabs();initQuota();initCodeTool();initFee();initCarePlan();initRenewal();initPhone();});
