
const CMS={2:10020,3:15460,4:18580,5:24100,6:28070,7:32090,8:36180};
const TRANSPORT_QUOTA={1:1680,2:1840,3:2000,4:2400};
const RATES={care:{second:.05,third:.16},professional:{second:.05,third:.16},respite:{second:.05,third:.16},transport:{second:.09,third:.27},assistive:{second:.10,third:.30}};
const SERVICE_DATA=[
{code:'BA01',name:'基本身體清潔',cat:'care',group:'BA居家服務',rateGroup:'care',price:260,unit:'次',desc:'協助梳頭修面、穿脫衣服、床上擦澡、床上洗頭、排泄物清理及相關協助。',talk:'重點是協助維持身體清潔與舒適，不是美容或額外整理。',note:'同一時段不可併同申報BA07及BA23。'},
{code:'BA02',name:'基本日常照顧',cat:'care',group:'BA居家服務',rateGroup:'care',price:195,unit:'30分鐘',desc:'協助翻身、移位、上下床、刷牙洗臉、穿脫衣物、如廁、更換尿片、倒尿桶、整理床鋪等。',talk:'日常照顧的萬用包，但仍以個案本人基本生活需求為限。',note:'以30分鐘為一單位，一日限三小時；不得與其他組合併用。'},
{code:'BA03',name:'測量生命徵象',cat:'care',group:'BA居家服務',rateGroup:'care',price:35,unit:'次',desc:'協助測量血壓、體溫、脈搏及呼吸並記錄，異常時回報。',talk:'量完不是結束，數值異常要回報並留下紀錄。',note:'一般服務前後觀察不一定適用。'},
{code:'BA04',name:'協助進食或管灌餵食',cat:'care',group:'BA居家服務',rateGroup:'care',price:130,unit:'餐',desc:'協助進食環境、安置、加熱飯菜、準備餐具、餵食或灌食與餐後善後。',talk:'重點是讓個案安全進食，不是煮飯。',note:'一餐為一組合；單純加熱飯菜屬本項。'},
{code:'BA05',name:'餐食照顧',cat:'care',group:'BA居家服務',rateGroup:'care',price:310,unit:'次/日',desc:'於案家備餐、備餐後用具與餐具清潔善後；或準備一日所需管灌飲食。',talk:'是備餐，不是幫全家煮飯或辦桌。',note:'同住長照對象共同使用時，僅擇一人扣額度與部分負擔。'},
{code:'BA07',name:'協助沐浴及洗頭',cat:'care',group:'BA居家服務',rateGroup:'care',price:325,unit:'次',desc:'協助至浴間、穿脫衣服、全身淋浴或盆浴、洗頭、排泄物清理與浴間整理。',talk:'洗澡是家中最容易跌倒的情境之一，重點是安全完成清潔。',note:'已包含BA01及BA23內容，同一時段不可併同申報。'},
{code:'BA08',name:'足部照護',cat:'care',group:'BA居家服務',rateGroup:'care',price:500,unit:'次',desc:'評估趾甲與足部皮膚，協助趾甲修剪、長繭處理、足部按摩與保養。',talk:'不是所有剪腳趾甲都叫BA08，一般日常修剪常回到BA02。',note:'限符合足部照護適用條件者。'},
{code:'BA09',name:'到宅沐浴車第一型',cat:'care',group:'BA居家服務',rateGroup:'care',price:2200,unit:'次',desc:'由到宅沐浴團隊攜帶設備至案家協助完成沐浴。',talk:'適合一般浴室無法安全洗澡、臥床或沐浴風險高者。',note:'依支付基準及服務提供規範辦理。'},
{code:'BA09a',name:'到宅沐浴車第二型',cat:'care',group:'BA居家服務',rateGroup:'care',price:2500,unit:'次',desc:'針對有管路、傷口或沐浴照護複雜度較高者提供到宅沐浴車服務。',talk:'第二型不是單純升級，是照護風險較高時使用。',note:'依支付基準及服務提供規範辦理。'},
{code:'BA10',name:'翻身拍背',cat:'care',group:'BA居家服務',rateGroup:'care',price:155,unit:'次',desc:'依指引協助扣背、震顫、翻身及相關照顧指導。',talk:'目的是預防壓傷及協助呼吸道照護，不是按摩服務。',note:'需留意個案耐受度及安全。'},
{code:'BA11',name:'肢體關節活動',cat:'care',group:'BA居家服務',rateGroup:'care',price:195,unit:'次',desc:'提供上下肢被動運動，或督促主動運動、站立練習。',talk:'重點是維持活動度，不是舒壓按摩。',note:'依指引執行，注意疼痛及安全。'},
{code:'BA12',name:'協助上下樓梯',cat:'care',group:'BA居家服務',rateGroup:'care',price:130,unit:'次',desc:'協助上下樓梯或輪椅搬運上下樓梯，含住家內及二樓以上家門口至一樓。',talk:'重點是一層樓以上的樓梯移動需求。',note:'使用電梯、爬梯機或樓梯升降椅者不適用。'},
{code:'BA13',name:'陪同外出',cat:'care',group:'BA居家服務',rateGroup:'care',price:195,unit:'30分鐘',desc:'協助外出工具安排、陪同外出及注意安全。',talk:'重點是陪同個案安全外出，不含交通工具費用。',note:'以30分鐘為一單位；符合BA12條件時可併同使用。'},
{code:'BA14',name:'陪同就醫',cat:'care',group:'BA居家服務',rateGroup:'care',price:685,unit:'次',desc:'協助掛號、就醫準備、陪同就診、聽取與轉知醫囑。',talk:'核心不是到醫院而已，而是陪同就診並協助轉知醫囑。',note:'不含交通費；自案家出門起算1.5小時內適用，超過可用BA13。'},
{code:'BA15',name:'家務協助',cat:'care',group:'BA居家服務',rateGroup:'care',price:195,unit:'30分鐘',desc:'協助主要生活空間清理、衣物洗滌晾曬、簡單縫補及相關家事服務。',talk:'沒有順便，也不是全家大掃除；以個案本人生活空間為主。',note:'非獨居者共用區域給付僅支付50%。'},
{code:'BA16',name:'代購或代領或代送服務',cat:'care',group:'BA居家服務',rateGroup:'care',price:130,unit:'次',desc:'協助餐食、食材、生活用品、藥品、郵寄、補助品或必要事項。',talk:'最重要是清單確認與記帳，避免後續爭議。',note:'以個案本人所需為限；距離自案家出門起算5公里內適用。'},
{code:'BA17a',name:'人工氣道管內分泌物抽吸',cat:'care',group:'BA居家服務',rateGroup:'care',price:75,unit:'次',desc:'協助人工氣道管內分泌物清潔、抽吸與移除。',talk:'風險較高，需由完成訓練人員依規定提供。',note:'如需口腔內分泌物處理可另加BA17b。'},
{code:'BA17b',name:'口腔內分泌物抽吸',cat:'care',group:'BA居家服務',rateGroup:'care',price:65,unit:'次',desc:'協助口腔內分泌物抽吸。',talk:'主要是口腔前段分泌物清除，呼吸異常需即時就醫。',note:'依照護規範與人員訓練限制辦理。'},
{code:'BA17c',name:'尿管及鼻胃管清潔固定',cat:'care',group:'BA居家服務',rateGroup:'care',price:50,unit:'次',desc:'協助尿管及鼻胃管之日常清潔與固定。',talk:'不是更換管路，是清潔、固定與觀察異常。',note:'管路異常需回報家屬或醫護。'},
{code:'BA17d1',name:'血糖機驗血糖',cat:'care',group:'BA居家服務',rateGroup:'care',price:50,unit:'次',desc:'依照護需求協助使用血糖機測量血糖。',talk:'血糖數值是監測，異常仍需依醫囑或聯繫醫療端。',note:'依服務規範與實際照顧需求辦理。'},
{code:'BA17d2',name:'甘油球通便',cat:'care',group:'BA居家服務',rateGroup:'care',price:50,unit:'次',desc:'依照護指示協助甘油球通便。',talk:'不能自行任意增加頻率，需依指示執行。',note:'若排便異常需回報。'},
{code:'BA17e',name:'依指示置入藥盒',cat:'care',group:'BA居家服務',rateGroup:'care',price:50,unit:'次',desc:'依指示協助將藥物置入藥盒。',talk:'放藥盒不等於調整藥物，藥物更動仍由醫師或藥師確認。',note:'需依明確用藥指示處理。'},
{code:'BA18',name:'安全看視',cat:'care',group:'BA居家服務',rateGroup:'care',price:200,unit:'30分鐘',desc:'至案家陪伴、支持、看視注意安全或協助日常生活參與。',talk:'限心智障礙者使用，重點是安全看視與支持。',note:'不得與其他組合併同使用，但可接續使用。'},
{code:'BA20',name:'陪伴服務',cat:'care',group:'BA居家服務',rateGroup:'care',price:175,unit:'30分鐘',desc:'至案家陪伴看視、日常生活參與，或讀紙本或電子新聞或書信。',talk:'陪伴不是單純聊天，而是支持生活參與與安全感。',note:'不得與其他組合併同使用，但可接續使用。'},
{code:'BA22',name:'巡視服務',cat:'care',group:'BA居家服務',rateGroup:'care',price:130,unit:'次',desc:'於特定時段至案家探視個案並進行簡易協助。',talk:'重點是確認安全與異常狀況，不是長時間照顧。',note:'依支付基準限制辦理。'},
{code:'BA23',name:'協助洗頭',cat:'care',group:'BA居家服務',rateGroup:'care',price:200,unit:'次',desc:'於床上或浴間單獨執行洗頭服務，含移位、穿脫衣服與環境整理。',talk:'主要困難是洗頭時，不一定要安排完整沐浴。',note:'同一時段不可併同申請BA01及BA07。'},
{code:'BA24',name:'協助排泄',cat:'care',group:'BA居家服務',rateGroup:'care',price:220,unit:'次',desc:'協助如廁、大小便、尿袋更換、造口袋清理、排泄物觀察與相關照顧。',talk:'不只是換尿布，也包含如廁移位與排泄物觀察。',note:'若於BA01或BA07過程中同時執行，不得併計。'},
{code:'BB01~BB14',name:'日間照顧',cat:'care',group:'BB日照',rateGroup:'care',price:675,unit:'日',desc:'白天至日照中心接受生活照顧、餐食、活動與安全看視。',talk:'像白天去上課活動，晚上再回家，不是安養院。',note:'實際價格依等級、服務型態與支付基準辦理。'},
{code:'BC01~BC14',name:'家庭托顧',cat:'care',group:'BC家庭托顧',rateGroup:'care',price:625,unit:'日',desc:'於家庭式照顧環境接受日間照顧。',talk:'人數較少、環境較像家，對部分長輩較容易適應。',note:'實際價格依等級、服務型態與支付基準辦理。'},
{code:'BD01',name:'社區式交通接送',cat:'care',group:'BD社區式交通',rateGroup:'care',price:100,unit:'趟',desc:'協助往返社區式服務據點。',talk:'搭配社區式服務，不是一般就醫交通。',note:'實際價格依支付基準與地方執行方式辦理。'},
{code:'CA07',name:'IADLs復能、ADLs復能照護',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4500,unit:'次',desc:'協助日常生活活動與工具性日常生活活動復能。',talk:'復能不是幫個案做，而是教個案盡量重新做到。',note:'依專業評估與照顧計畫執行。'},
{code:'CA08',name:'個別化服務計畫擬定與執行',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4500,unit:'次',desc:'依個案需求擬定並執行個別化復能服務計畫。',talk:'依個案狀況設定目標，不是每個人做一樣的訓練。',note:'依專業評估與支付基準辦理。'},
{code:'CB01a',name:'營養照護',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4000,unit:'次',desc:'由營養專業人員提供營養評估與飲食建議。',talk:'營養師不是只開菜單，也會依疾病與身體狀況調整飲食。',note:'依專業評估與支付基準辦理。'},
{code:'CB02',name:'進食與吞嚥照護',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4000,unit:'次',desc:'針對進食安全、吞嚥困難提供評估與建議。',talk:'吃飯常咳嗽、喝水容易嗆到，就很適合評估吞嚥照護。',note:'依專業評估與支付基準辦理。'},
{code:'CB03',name:'困擾行為照護',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4000,unit:'次',desc:'針對困擾行為提供照顧策略與指導。',talk:'不是教長輩聽話，而是找出行為背後原因，讓照顧比較順。',note:'依專業評估與支付基準辦理。'},
{code:'CB04',name:'臥床或長期活動受限照護',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:4000,unit:'次',desc:'針對臥床、壓傷風險、擺位與照顧技巧提供指導。',talk:'臥床照護重點是皮膚、擺位、翻身與照顧技巧。',note:'依專業評估與支付基準辦理。'},
{code:'CC01',name:'居家環境安全或無障礙空間規劃',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:2000,unit:'次',desc:'評估居家安全、輔具及無障礙改善需求。',talk:'有時不是長輩退化太快，而是家裡環境不適合現在的身體狀況。',note:'依專業評估與支付基準辦理。'},
{code:'CD02',name:'居家護理指導與諮詢',cat:'care',group:'C碼專業服務',rateGroup:'professional',price:2000,unit:'次',desc:'提供傷口、管路、慢性病與照護技巧指導。',talk:'護理不只是換藥，也包含家屬照顧技巧和異常觀察。',note:'依專業評估與支付基準辦理。'},
{code:'GA09',name:'居家喘息',cat:'care',group:'G碼喘息',rateGroup:'respite',price:770,unit:'2小時',desc:'照服員到家中短時間照顧，讓主要照顧者休息。',talk:'照顧者休息不是偷懶，是讓照顧走得更久。',note:'依喘息額度與支付基準辦理。'},
{code:'SC09',name:'短照服務',cat:'care',group:'短照服務',rateGroup:'respite',price:770,unit:'2小時',desc:'外籍看護工家庭可依規定使用短期替代照顧服務。',talk:'外看請假、返國或家庭短期照顧人力不足時，可評估使用。',note:'外看短照額度：2–6級87,780元；7–8級71,610元。'},
{code:'DA-1',name:'交通接送第一區',cat:'transport',group:'DA交通接送',rateGroup:'transport',price:1680,unit:'月額度',desc:'交通接送第一區每月額度。',talk:'此為月額度，不是單趟車資；單趟計價依地方公告。',note:'第二類9%，第三類27%。'},
{code:'DA-2',name:'交通接送第二區',cat:'transport',group:'DA交通接送',rateGroup:'transport',price:1840,unit:'月額度',desc:'交通接送第二區每月額度。',talk:'此為月額度，不是單趟車資；單趟計價依地方公告。',note:'第二類9%，第三類27%。'},
{code:'DA-3',name:'交通接送第三區',cat:'transport',group:'DA交通接送',rateGroup:'transport',price:2000,unit:'月額度',desc:'交通接送第三區每月額度。',talk:'此為月額度，不是單趟車資；單趟計價依地方公告。',note:'第二類9%，第三類27%。'},
{code:'DA-4',name:'交通接送第四區',cat:'transport',group:'DA交通接送',rateGroup:'transport',price:2400,unit:'月額度',desc:'交通接送第四區每月額度。',talk:'此為月額度，不是單趟車資；單趟計價依地方公告。',note:'第二類9%，第三類27%。'},
{code:'E-WC',name:'輪椅',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:5000,unit:'件',visualClass:'aid-wheelchair',visual:'♿',visualText:'輪椅：坐著推行的移動輔具',desc:'協助行走困難或耐力不足者移動。',talk:'家屬看到輪椅通常最容易理解：不是不能走才可用，而是外出或長距離移動不安全時可評估。',note:'實際補助金額依輔具評估、規格與補助基準辦理。'},
{code:'E-WALKER',name:'助行器',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:1500,unit:'件',visualClass:'aid-walker',visual:'🚶‍♀️',visualText:'助行器：前方框架協助站立行走',desc:'協助步態不穩、下肢無力者行走。',talk:'比拐杖支撐面更大，適合平衡差或剛出院需要支撐者。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-CANE',name:'四腳拐',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:1000,unit:'件',visualClass:'aid-cane',visual:'🦯',visualText:'四腳拐：底部四支腳，比單拐穩',desc:'提供行走時額外支撐。',talk:'重點是底部有四個支撐點，平衡通常比單拐更穩。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-SHOWER',name:'沐浴椅',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:1200,unit:'件',visualClass:'aid-shower',visual:'🪑',visualText:'沐浴椅：放浴室坐著洗澡',desc:'協助站立不穩或沐浴易跌倒者坐姿沐浴。',talk:'家屬常問是不是普通椅子；重點是防水、防滑、適合浴室使用。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-COMMODE',name:'便盆椅',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:2000,unit:'件',visualClass:'aid-commode',visual:'🚽',visualText:'便盆椅：床邊可坐著如廁',desc:'協助夜間如廁、移位困難或廁所距離遠者。',talk:'不是馬桶壞掉才用，是降低半夜走到浴廁跌倒的風險。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-AIR',name:'氣墊床',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:8000,unit:'件',visualClass:'aid-air',visual:'🛏️',visualText:'氣墊床：臥床者減少壓力集中',desc:'協助長期臥床者降低壓傷風險。',talk:'有壓傷風險時很常用，但仍要搭配翻身、皮膚觀察與照顧技巧。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-BED',name:'電動照顧床',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:20000,unit:'件',visualClass:'aid-bed',visual:'🛌',visualText:'電動床：可升降背部或床高',desc:'協助上下床、翻身、照顧者照顧操作。',talk:'不是完全臥床才可能需要；上下床困難、照顧負荷高也可評估。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'E-HOIST',name:'移位機',cat:'assistive',group:'E碼輔具',rateGroup:'assistive',price:40000,unit:'件',visualClass:'aid-hoist',visual:'🏗️',visualText:'移位機：協助床椅移位的吊掛設備',desc:'協助移位困難、照顧者搬抱風險高者。',talk:'重點是降低照顧者搬抱傷害，也讓個案移位更安全。',note:'實際補助金額依評估與補助基準辦理。'},
{code:'F-RAMP',name:'斜坡板／門檻改善',cat:'assistive',group:'F碼居家無障礙',rateGroup:'assistive',price:10000,unit:'案',visualClass:'aid-ramp',visual:'↗️',visualText:'斜坡板：讓輪椅或助行器通過高低差',desc:'改善門檻、高低差或輪椅通行困難。',talk:'家裡小門檻也可能造成跌倒或輪椅卡住，需看實際動線。',note:'實際補助金額依評估與工程補助基準辦理。'},
{code:'F-BAR',name:'扶手',cat:'assistive',group:'F碼居家無障礙',rateGroup:'assistive',price:5000,unit:'案',visualClass:'aid-bar',visual:'🧱',visualText:'扶手：牆面支撐，協助起身與行走',desc:'於浴室、走道、床邊或馬桶旁設置扶手，協助移動及起身。',talk:'扶手不是裝越多越好，要裝在真的用得到、抓得到的位置。',note:'實際補助金額依評估與工程補助基準辦理。'},
{code:'F-BATH',name:'浴室防滑改善',cat:'assistive',group:'F碼居家無障礙',rateGroup:'assistive',price:10000,unit:'案',visualClass:'aid-bath',visual:'🛁',visualText:'浴室防滑：降低洗澡跌倒風險',desc:'改善浴室地面濕滑、排水或移動安全。',talk:'浴室是跌倒熱區，防滑與扶手常需要一起評估。',note:'實際補助金額依評估與工程補助基準辦理。'}
,{code:'AA01',name:'照顧計畫擬定與服務連結',cat:'aa',group:'AA照顧管理',rateGroup:'care',price:1000,unit:'次',desc:'A單位個案管理員進行照顧計畫擬定、服務連結、需求確認與資源安排。',talk:'這是個管針對新案或需要重新擬定計畫時的核心工作，不是單純打電話。',note:'實際核定與申報依照管平台及地方規範辦理。'}
,{code:'AA02',name:'照顧管理',cat:'aa',group:'AA照顧管理',rateGroup:'care',price:700,unit:'月',desc:'個案管理員每月追蹤個案服務使用情形、滿意度、照顧需求變化及資源連結。',talk:'AA02的重點是持續追蹤計畫是否適切，避免每月紀錄重複複製貼上。',note:'每月電訪或追蹤應包含服務使用、需求變化、滿意度與後續處置。'}
,{code:'AA08',name:'照顧困難或特殊需求加計',cat:'aa',group:'AA照顧管理',rateGroup:'care',price:0,unit:'依規定',desc:'針對符合照顧困難或特殊需求原則之個案，依規定敘明訪談時間、提出對象及原因。',talk:'若要核定AA08，不能只寫家屬很辛苦，要說清楚符合哪項原則與具體狀況。',note:'需依主管機關函釋、地方規定及照管平台審認辦理。'}
,{code:'AA09',name:'特殊照顧管理需求加計',cat:'aa',group:'AA照顧管理',rateGroup:'care',price:0,unit:'依規定',desc:'針對符合特殊照顧管理需求之個案，於計畫中敘明原因及相關評估依據。',talk:'若屬地方政府審視認有需要者，建議補充評估量表相關項目與具體事件。',note:'需依主管機關函釋、地方規定及照管平台審認辦理。'}

];
