const money = n => Number(n || 0).toLocaleString('zh-TW');
const floorMoney = (price, rate) => Math.floor(Number(price || 0) * rate);

const cmsLevels = {2:10020,3:15460,4:18580,5:24100,6:28070,7:32090,8:36180};
const transportLimits = {first:1680,second:1840,third:2000,fourth:2400};
const respiteLimits = level => Number(level) >= 7 ? 48510 : 32340;
const shortStayForeignLimits = level => Number(level) >= 7 ? 71610 : 87780;
const assistiveLimits = {group1:40000,group2:60000};
const ratesByType = {
  care:{second:.05,third:.16,label:'照顧及專業服務'},
  transport:{second:.09,third:.27,label:'交通接送'},
  assistive:{second:.10,third:.30,label:'輔具及居家無障礙'},
  respite:{second:.05,third:.16,label:'喘息服務'},
  free:{second:0,third:0,label:'免部分負擔'}
};

const codeGroups = [
  {key:'care', label:'照顧及專業服務＋喘息'},
  {key:'transport', label:'交通接送'},
  {key:'assistive', label:'輔具及居家無障礙'}
];

const services = [
{code:'AA01',name:'照顧計畫擬訂與服務連結',category:'AA照顧管理',type:'free',price:1700,unit:'次',desc:'承接轉介、家訪討論需求、擬訂照顧計畫並連結服務。每六個月重新擬訂或複評等級改變可申報。',note:'不扣額度且免部分負擔；不得與AA02同月併計。',plain:'個管開案、擬計畫與服務連結的核心碼。'},
{code:'AA02',name:'照顧管理',category:'AA照顧管理',type:'free',price:400,unit:'次',desc:'調整照顧計畫、追蹤服務連結、每月品質追蹤、諮詢申訴處理與資源連結。',note:'不扣額度且免部分負擔；不得與AA01同月併計。',plain:'個管後續追蹤、異動與服務品質管理。'},
{code:'AA03',name:'照顧服務員配合專業服務',category:'AA政策鼓勵',type:'free',price:600,unit:'次',desc:'照服員於專業服務提供時同行學習，並同時段提供指定居家照顧服務。',note:'每個C碼專業服務組合只能申請一次；免部分負擔。',plain:'讓居服員學會專業服務後續怎麼配合。'},
{code:'AA04',name:'於臨終日提供服務加計',category:'AA政策鼓勵',type:'free',price:1200,unit:'次',desc:'臨終日或前一日提供BA碼，或後一日提供BA01可加計。',note:'限申請一次，不扣額度且免部分負擔。',plain:'臨終前後照顧服務加計。'},
{code:'AA05',name:'照顧困難之服務加計',category:'AA加計',type:'free',price:200,unit:'日',desc:'抗拒或攻擊行為、傳染性疾病、特定身障或失智、重度特殊疾病等照顧困難情形加計。',note:'一日限一次；BA16除外；不扣額度。',plain:'個案照顧難度高時的服務加計。'},
{code:'AA06',name:'身體照顧困難加計',category:'AA加計',type:'free',price:200,unit:'日',desc:'管路／傷口／燒燙傷、移位困難且體重>70公斤、12歲以下等身體照顧困難情形加計。',note:'每日以一次為限；不扣額度。',plain:'身體照顧本身比較費力或風險較高時加計。'},
{code:'AA07',name:'家庭照顧功能微弱之服務加計',category:'AA加計',type:'free',price:760,unit:'月',desc:'CMS4以上且家庭照顧者75歲以上、領有身障證明或獨居者，提供指定BA碼可加計。',note:'每月申請一次；不扣額度。',plain:'家庭支持弱、照顧資源不足時的加計。'},
{code:'AA08',name:'晚間服務',category:'AA加計',type:'free',price:385,unit:'日',desc:'晚上8點至12點提供照顧及專業服務時加計。',note:'同日AA08及AA09不得同時申請；不扣額度。',plain:'晚間服務加計。'},
{code:'AA09',name:'例假日服務',category:'AA加計',type:'free',price:770,unit:'日',desc:'週六、週日或國定假日提供照顧及專業服務、喘息服務時加計。',note:'同服務單位同個案一日限一次；不扣額度。',plain:'假日服務加計。'},
{code:'AA10',name:'夜間緊急服務',category:'AA加計',type:'free',price:1000,unit:'日',desc:'晚上12點至隔日6點緊急提供非照顧計畫既定照顧服務加計。',note:'一日為一給付單位；不扣額度。',plain:'半夜臨時緊急服務。'},
{code:'AA11',name:'照顧服務員進階訓練',category:'AA加計',type:'free',price:50,unit:'日',desc:'照服員針對失智、特定身障、腦麻、脊損等對象提供指定服務時加計。',note:'服務人員需符合訓練規定；每日限一次。',plain:'服務特殊需求個案時，鼓勵完訓照服員投入。'},
{code:'AA12',name:'開立醫師意見書',category:'AA照顧管理',type:'free',price:1500,unit:'次',desc:'醫師家訪評估長照醫事照護需求，提出意見並上傳系統。',note:'每年上限二次；不扣額度。',plain:'醫師到宅評估長照醫事照護需求。'},

{code:'BA01',name:'基本身體清潔',category:'BA居家服務',type:'care',price:260,unit:'次',desc:'協助梳頭修面、穿脫衣服、床上擦澡、床上洗頭、排泄物清理等。',note:'同時段不可併BA07、BA23；原則一日一組合。',plain:'偏向床上擦澡與基本清潔，不是完整進浴室洗澡。'},
{code:'BA02',name:'基本日常照顧',category:'BA居家服務',type:'care',price:195,unit:'30分鐘',desc:'翻身、移位、如廁、更換尿片、整理床、更換床單、協助用藥等日常照顧。',note:'每30分鐘一單位，一日限3小時；不得與其他組合併用。',plain:'日常照顧萬用碼，但不能什麼都硬塞。'},
{code:'BA03',name:'測量生命徵象',category:'BA居家服務',type:'care',price:35,unit:'次',desc:'測量血壓、體溫、脈搏、呼吸並記錄，異常時回報。',note:'若只是服務前後一般觀察，不適用。',plain:'有疾病監測需求才比較適合，不是洗澡前順手量血壓。'},
{code:'BA04',name:'協助進食或管灌餵食',category:'BA居家服務',type:'care',price:130,unit:'餐',desc:'準備進食環境、加熱飯菜、協助餵食或灌食、觀察反應與善後。',note:'一餐為一組合；單純加熱或管灌食品屬本項。',plain:'重點是協助個案安全進食，不是煮飯。'},
{code:'BA05',name:'餐食照顧',category:'BA居家服務',type:'care',price:310,unit:'次/日',desc:'在案家備餐及善後，或準備一日所需管灌飲食。',note:'同住長照對象共同使用，僅擇一人扣額度；單純加熱屬BA04。',plain:'備餐是以個案餐食需求為主，不是煮全家晚餐。'},
{code:'BA07',name:'協助沐浴及洗頭',category:'BA居家服務',type:'care',price:325,unit:'次',desc:'協助至浴間、穿脫衣服、全身淋浴／坐浴／盆浴、洗頭、排泄物清理及浴室整理。',note:'已包含BA01與BA23，同時段不可併同申報。',plain:'完整洗澡服務包，包含洗前準備與洗後整理。'},
{code:'BA08',name:'足部照護',category:'BA居家服務',type:'care',price:500,unit:'次',desc:'評估趾甲與足部皮膚、修剪問題甲、處理長繭、足部保養與紀錄。',note:'限糖尿病且問題清單符合條件；日常趾甲修剪屬BA02。',plain:'不是所有剪腳趾甲都叫BA08。'},
{code:'BA09',name:'到宅沐浴車服務－第一型',category:'BA居家服務',type:'care',price:2200,unit:'次',desc:'利用專用車輛與行動浴槽到宅提供全身式沐浴。',note:'限CMS5-8；至少三位完成訓練之照服員團隊。',plain:'一般浴室無法安全洗澡時，可評估到宅沐浴車。'},
{code:'BA09a',name:'到宅沐浴車服務－第二型',category:'BA居家服務',type:'care',price:2500,unit:'次',desc:'針對留置管路、呼吸器、燒燙傷、三級傷口等高照護需求者提供沐浴車服務，含護理評估與衛教。',note:'限CMS5-8且符合條件；需1名護理人員與2名照服員。',plain:'不是加價升級，是照顧風險較高才適用。'},
{code:'BA10',name:'翻身拍背',category:'BA居家服務',type:'care',price:155,unit:'次',desc:'協助扣背、震顫、翻身及相關照顧指導。',note:'依衛福部指引執行。',plain:'重點是預防壓傷與呼吸道照顧，不是按摩。'},
{code:'BA11',name:'肢體關節活動',category:'BA居家服務',type:'care',price:195,unit:'次',desc:'上肢、下肢被動運動，或督促主動運動與站立練習。',note:'依指引執行，注意疼痛與耐受度。',plain:'維持活動度，不是復健治療也不是按摩。'},
{code:'BA12',name:'協助上下樓梯',category:'BA居家服務',type:'care',price:130,unit:'次',desc:'協助上下樓梯或輪椅搬運上下樓梯，一層樓以上適用。',note:'限問題清單有移位或上下樓梯問題；使用電梯、爬梯機、樓梯升降椅不適用。',plain:'重點是一層樓以上的上下樓協助。'},
{code:'BA13',name:'陪同外出',category:'BA居家服務',type:'care',price:195,unit:'30分鐘',desc:'安排外出工具、陪同外出並注意安全，外出目的含購物、社交、辦事、散步、定期復健或透析等。',note:'不含交通工具費；符合BA12可併同使用。',plain:'重點是全程陪同與安全，不是交通車。'},
{code:'BA14',name:'陪同就醫',category:'BA居家服務',type:'care',price:685,unit:'次',desc:'協助掛號、就醫準備、陪同就診、聽取並轉知醫囑與注意事項。',note:'不適用定期復健或透析；自案家出門1.5小時內，超過可用BA13。',plain:'有實際陪診、聽醫囑、轉知醫囑才是核心。'},
{code:'BA15',name:'家務協助',category:'BA居家服務',type:'care',price:195,unit:'30分鐘',desc:'依獨居與否協助生活空間清理、衣物洗滌、晾曬、烘乾、熨燙、簡單縫補等。',note:'非大掃除；非獨居共用區域僅給付50%，另50%自費。',plain:'以個案使用空間與個案需求為主，不是全家大掃除。'},
{code:'BA16',name:'代購或代領或代送服務',category:'BA居家服務',type:'care',price:130,unit:'次',desc:'代購餐食、食材、生活用品、藥品、郵寄、補助品、衣物床單送洗取回等。',note:'限個案本人所需；距離自案家出門5公里內適用。',plain:'最重要是買什麼、花多少、找多少要記清楚。'},
{code:'BA17a',name:'人工氣道管內分泌物抽吸',category:'BA居家服務',type:'care',price:75,unit:'次',desc:'人工氣道管內分泌物清潔、抽吸與氣切造口簡易照顧。',note:'需完成認可訓練；原則一日三組合為限。',plain:'高風險照顧，異常要即時回報。'},
{code:'BA17b',name:'口腔內分泌物抽吸',category:'BA居家服務',type:'care',price:65,unit:'次',desc:'口腔內（懸壅垂之前）分泌物清潔、抽吸與移除。',note:'需完成認可訓練；原則一日三組合為限。',plain:'口腔前段分泌物抽吸，不是氣管內抽吸。'},
{code:'BA17c',name:'尿管及鼻胃管之清潔與固定',category:'BA居家服務',type:'care',price:50,unit:'次',desc:'尿管清潔、更換固定膠布；鼻胃管鼻部清潔、確認位置與更換固定膠布。',note:'原則每週七組合為限。',plain:'是清潔與固定，不是更換管路。'},
{code:'BA17d1',name:'血糖機驗血糖',category:'BA居家服務',type:'care',price:50,unit:'次',desc:'使用攜帶式血糖機協助驗血糖。',note:'原則每日一組合為限。',plain:'協助監測，異常仍要依醫囑或就醫。'},
{code:'BA17d2',name:'甘油球通便',category:'BA居家服務',type:'care',price:50,unit:'次',desc:'協助甘油球通便。',note:'原則每週三組合為限；特殊情況需經評估審核。',plain:'不能自行任意增加頻率。'},
{code:'BA17e',name:'依指示置入藥盒',category:'BA居家服務',type:'care',price:50,unit:'次',desc:'依照藥袋指示置入藥盒。',note:'原則每週一組合為限。',plain:'照藥袋放藥盒，不是調整藥物。'},
{code:'BA18',name:'安全看視',category:'BA居家服務',type:'care',price:200,unit:'30分鐘',desc:'至案家陪伴、支持、看視注意安全或協助日常生活參與。',note:'限心智障礙者使用；不得與其他組合併同使用，但可接續。',plain:'安全看視與陪伴支持，限心智障礙者。'},
{code:'BA20',name:'陪伴服務',category:'BA居家服務',type:'care',price:175,unit:'30分鐘',desc:'至案家陪伴看視、日常生活參與，或讀紙本／電子新聞或書信。',note:'不得與其他組合併同使用，但可接續。',plain:'陪伴不是單純聊天，是支持生活參與與安全。'},
{code:'BA22',name:'巡視服務',category:'BA居家服務',type:'care',price:130,unit:'次',desc:'上午6點至晚上8點至案家探視並進行簡易協助，至少三次。',note:'不得搭配其他照顧組合。',plain:'短時間確認安全與簡易協助，不是長時間照顧。'},
{code:'BA23',name:'協助洗頭',category:'BA居家服務',type:'care',price:200,unit:'次',desc:'單獨協助洗頭，含移位／引導、穿脫衣服、局部清潔、環境準備與整理。',note:'同時段不可併BA01及BA07。',plain:'只有洗頭需求時，不一定要開完整沐浴。'},
{code:'BA24',name:'協助排泄',category:'BA居家服務',type:'care',price:220,unit:'次',desc:'協助如廁、小便大便、尿袋更換、造口袋清理、排泄物觀察與失禁處理等。',note:'如於BA01或BA07過程中同時執行，不得併計。',plain:'不只是換尿布，也包含如廁移位與排泄照顧。'},

{code:'BB01',name:'日間照顧全日－第一型',category:'BB日間照顧',type:'care',price:675,unit:'日',desc:'生活照顧、健康促進、文康活動、家屬指導諮詢、備餐服務。',note:'適用CMS2；交通另計。',plain:'白天去日照中心活動與受照顧。'},
{code:'BB02',name:'日間照顧半日－第一型',category:'BB日間照顧',type:'care',price:340,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS2；同日不得申請二次。',plain:'半天日照。'},
{code:'BB03',name:'日間照顧全日－第二型',category:'BB日間照顧',type:'care',price:840,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS3；交通另計。',plain:'CMS3全日照顧。'},
{code:'BB04',name:'日間照顧半日－第二型',category:'BB日間照顧',type:'care',price:420,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS3；同日不得申請二次。',plain:'CMS3半日照顧。'},
{code:'BB05',name:'日間照顧全日－第三型',category:'BB日間照顧',type:'care',price:920,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS4。',plain:'CMS4全日照顧。'},
{code:'BB06',name:'日間照顧半日－第三型',category:'BB日間照顧',type:'care',price:460,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS4。',plain:'CMS4半日照顧。'},
{code:'BB07',name:'日間照顧全日－第四型',category:'BB日間照顧',type:'care',price:1045,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS5。',plain:'CMS5全日照顧。'},
{code:'BB08',name:'日間照顧半日－第四型',category:'BB日間照顧',type:'care',price:525,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS5。',plain:'CMS5半日照顧。'},
{code:'BB09',name:'日間照顧全日－第五型',category:'BB日間照顧',type:'care',price:1130,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS6。',plain:'CMS6全日照顧。'},
{code:'BB10',name:'日間照顧半日－第五型',category:'BB日間照顧',type:'care',price:565,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS6。',plain:'CMS6半日照顧。'},
{code:'BB11',name:'日間照顧全日－第六型',category:'BB日間照顧',type:'care',price:1210,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS7。',plain:'CMS7全日照顧。'},
{code:'BB12',name:'日間照顧半日－第六型',category:'BB日間照顧',type:'care',price:605,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS7。',plain:'CMS7半日照顧。'},
{code:'BB13',name:'日間照顧全日－第七型',category:'BB日間照顧',type:'care',price:1285,unit:'日',desc:'日間照顧全日服務。',note:'適用CMS8。',plain:'CMS8全日照顧。'},
{code:'BB14',name:'日間照顧半日－第七型',category:'BB日間照顧',type:'care',price:645,unit:'半日',desc:'日間照顧半日服務。',note:'適用CMS8。',plain:'CMS8半日照顧。'},

{code:'BC01',name:'家庭托顧全日－第一型',category:'BC家庭托顧',type:'care',price:625,unit:'日',desc:'家庭式環境中提供身體照顧、日常生活照顧、安全照顧、備餐。',note:'適用CMS2；交通另計。',plain:'人數較少、類似家庭環境的日間照顧。'},
{code:'BC02',name:'家庭托顧半日－第一型',category:'BC家庭托顧',type:'care',price:315,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS2。',plain:'CMS2半日家托。'},
{code:'BC03',name:'家庭托顧全日－第二型',category:'BC家庭托顧',type:'care',price:760,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS3。',plain:'CMS3全日家托。'},
{code:'BC04',name:'家庭托顧半日－第二型',category:'BC家庭托顧',type:'care',price:380,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS3。',plain:'CMS3半日家托。'},
{code:'BC05',name:'家庭托顧全日－第三型',category:'BC家庭托顧',type:'care',price:785,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS4。',plain:'CMS4全日家托。'},
{code:'BC06',name:'家庭托顧半日－第三型',category:'BC家庭托顧',type:'care',price:395,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS4。',plain:'CMS4半日家托。'},
{code:'BC07',name:'家庭托顧全日－第四型',category:'BC家庭托顧',type:'care',price:880,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS5。',plain:'CMS5全日家托。'},
{code:'BC08',name:'家庭托顧半日－第四型',category:'BC家庭托顧',type:'care',price:440,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS5。',plain:'CMS5半日家托。'},
{code:'BC09',name:'家庭托顧全日－第五型',category:'BC家庭托顧',type:'care',price:960,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS6。',plain:'CMS6全日家托。'},
{code:'BC10',name:'家庭托顧半日－第五型',category:'BC家庭托顧',type:'care',price:480,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS6。',plain:'CMS6半日家托。'},
{code:'BC11',name:'家庭托顧全日－第六型',category:'BC家庭托顧',type:'care',price:980,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS7。',plain:'CMS7全日家托。'},
{code:'BC12',name:'家庭托顧半日－第六型',category:'BC家庭托顧',type:'care',price:490,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS7。',plain:'CMS7半日家托。'},
{code:'BC13',name:'家庭托顧全日－第七型',category:'BC家庭托顧',type:'care',price:1040,unit:'日',desc:'家庭托顧全日服務。',note:'適用CMS8。',plain:'CMS8全日家托。'},
{code:'BC14',name:'家庭托顧半日－第七型',category:'BC家庭托顧',type:'care',price:520,unit:'半日',desc:'家庭托顧半日服務。',note:'適用CMS8。',plain:'CMS8半日家托。'},
{code:'BD01',name:'社區式協助沐浴',category:'BD社區式服務',type:'care',price:200,unit:'次',desc:'於日照中心、小規模多機能或托顧家庭浴間協助沐浴。',note:'社區式服務場所執行。',plain:'不是到宅，是在社區式服務點洗澡。'},
{code:'BD02',name:'社區式晚餐',category:'BD社區式服務',type:'care',price:150,unit:'次',desc:'準備晚餐、協助進食或餵食及飯後口腔清潔。',note:'於日照中心、小規模多機能或托顧家庭執行。',plain:'社區式服務中的晚餐照顧。'},
{code:'BD03',name:'社區式服務交通接送',category:'BD社區式服務',type:'care',price:115,unit:'趟',desc:'接送個案往返居家與日照、托顧家庭、巷弄站、文健站、失智據點、輔具中心等。',note:'住家與服務機構距離10公里內適用；以一趟為單位。',plain:'搭配社區式服務的交通，不是一般就醫交通。'},

{code:'CA07',name:'IADLs復能、ADLs復能照護',category:'CA專業服務',type:'care',price:4500,unit:'組',desc:'評估並擬訂IADLs、ADLs復能計畫，提供指導措施與記錄。',note:'三次措施含評估為一組。',plain:'不是幫個案做，而是教個案盡量重新做到。'},
{code:'CA08',name:'個別化服務計畫（ISP）擬定與執行',category:'CA專業服務',type:'care',price:6000,unit:'組',desc:'針對慢性精神病、自閉症、智能障礙、失智等擬定並執行個別化服務計畫。',note:'四次措施含評估與ISP擬定為一組。',plain:'針對生活自理、社交、休閒、健康促進與社區適應設定目標。'},
{code:'CB01a',name:'營養照護',category:'CB專業服務',type:'care',price:4500,unit:'組',desc:'評估營養照護需求、提供指導措施、轉介必要醫療處置與紀錄。',note:'三次措施含評估為一組。',plain:'營養師不只是開菜單，會依疾病與身體狀況調整飲食。'},
{code:'CB02',name:'進食與吞嚥照護',category:'CB專業服務',type:'care',price:9000,unit:'組',desc:'評估進食與吞嚥需求，提供指導措施與紀錄。',note:'六次措施含評估為一組。',plain:'常嗆咳、喝水易嗆、吃飯時間太長可評估。'},
{code:'CB03',name:'困擾行為照護',category:'CB專業服務',type:'care',price:4500,unit:'組',desc:'評估困擾行為照護需求，提供照顧策略與紀錄。',note:'三次措施含評估為一組。',plain:'不是叫長輩聽話，是找出行為背後原因。'},
{code:'CB04',name:'臥床或長期活動受限照護',category:'CB專業服務',type:'care',price:9000,unit:'組',desc:'評估長期臥床或活動受限照護需求，提供指導措施。',note:'六次措施含評估為一組。',plain:'重點是皮膚、擺位、翻身與照顧技巧。'},
{code:'CC01',name:'居家環境安全或無障礙空間規劃',category:'CC專業服務',type:'care',price:2000,unit:'組',desc:'提供活動照顧策略、家具擺設、輔具使用、居家安全環境改善建議。',note:'二次措施含評估為一組；所需輔具或修繕另依規定。',plain:'不是直接補助施工，是先評估環境與安全。'},
{code:'CD02',name:'居家護理指導與諮詢',category:'CD專業服務',type:'care',price:6000,unit:'組',desc:'護理需求與家庭評估、擬定護理計畫、照護問題處理與諮詢。',note:'三次措施含評估加一次評值為一組。',plain:'傷口、管路、慢性病照護與家屬照顧技巧指導。'},

{code:'DA01',name:'交通接送',category:'DA交通接送',type:'transport',price:null,unit:'月額度',desc:'往返居家至醫療院所就醫、定期復健或透析治療之交通接送；必要轉乘或接駁經核認可不限居家或醫療院所。',note:'單趟支付價格由地方主管機關訂定公告；中央附表列第一區至第四區每月額度。',plain:'這裡顯示的是每月額度，不是單趟車資。'},

{code:'GA03',name:'日間照顧中心喘息服務－全日',category:'GA喘息服務',type:'respite',price:1250,unit:'日',desc:'至日照中心接受照顧、停留，含護理照護、沐浴、進食、服藥、活動安排等。',note:'含交通接送。',plain:'白天去日照喘息，讓照顧者休息。'},
{code:'GA04',name:'日間照顧中心喘息服務－半日',category:'GA喘息服務',type:'respite',price:625,unit:'半日',desc:'日照中心半日喘息服務。',note:'含交通接送。',plain:'半天日照喘息。'},
{code:'GA05',name:'機構住宿式喘息服務',category:'GA喘息服務',type:'respite',price:2310,unit:'日',desc:'至住宿式長照機構接受短暫照顧，含24小時照顧、護理照護、沐浴、進食、服藥、活動等。',note:'以一日24小時為單位；含交通接送。',plain:'短期住機構喘息，不是永久入住。'},
{code:'GA06',name:'小規模多機能服務－夜間喘息',category:'GA喘息服務',type:'respite',price:2000,unit:'次',desc:'夜間至小規模多機能中心接受生活照顧、沐浴、進食、服藥、住宿等。',note:'夜間為下午6點至翌日上午8點；含交通接送。',plain:'夜間有人接手照顧。'},
{code:'GA07',name:'巷弄長照站喘息服務',category:'GA喘息服務',type:'respite',price:170,unit:'小時',desc:'至巷弄長照站接受照顧、停留，含進食、服藥、活動安排等。',note:'以小時為單位。',plain:'短時段社區據點喘息。'},
{code:'GA09',name:'居家喘息服務',category:'GA喘息服務',type:'respite',price:770,unit:'2小時',desc:'照服員到宅提供身體照顧，含如廁、沐浴、進食、服藥、翻身拍背、簡單肢體活動、上下床、陪同運動等。',note:'以2小時為單位，單日上限10小時；有陪同就醫需求可加計BA14。',plain:'照顧者休息不是偷懶，是讓照顧能走更久。'},
];

const assistiveServices = [
{code:'EA01',name:'馬桶增高器、便盆椅或沐浴椅',price:1200,unit:'購置',img:'toilet_chair',desc:'協助如廁或沐浴坐姿安全。',note:'限購置；最低使用年限3年。'},
{code:'EB01',name:'單支拐杖－不鏽鋼製',price:1000,unit:'購置',img:'cane',desc:'提供步行支撐。',note:'限購置；最低使用年限5年。'},
{code:'EB02',name:'單支拐杖－鋁製',price:500,unit:'購置',img:'cane',desc:'較輕量的單支拐杖。',note:'限購置；最低使用年限3年。'},
{code:'EB03',name:'助行器',price:800,unit:'購置',img:'walker',desc:'提供步行穩定支撐。',note:'限購置；最低使用年限3年。'},
{code:'EB04',name:'帶輪型助步車（助行椅）',price:3000,rent:300,unit:'月/購置',img:'rollator',desc:'具手控煞車、煞車鎖定及臨時座位。',note:'可租賃可購置；需評估。'},
{code:'EC01',name:'輪椅-A款（非輕量化量產型）',price:3500,unit:'購置',img:'wheelchair',desc:'基本量產輪椅，應配備骨盆帶。',note:'EC01-EC03僅能擇一。'},
{code:'EC02',name:'輪椅-B款（輕量化量產型）',price:4000,rent:450,unit:'月/購置',img:'wheelchair',desc:'輕量化量產輪椅。',note:'EC01-EC03僅能擇一。'},
{code:'EC03',name:'輪椅-C款（量身訂製型）',price:9000,unit:'購置',img:'wheelchair_custom',desc:'符合特殊座寬、載重或個別化需求之輪椅。',note:'需輔具評估；免部分負擔。'},
{code:'EC04',name:'輪椅附加功能-A款（利於移位）',price:5000,rent:150,unit:'月/購置',img:'wheelchair',desc:'可拆掀式扶手及可拆卸式腳靠。',note:'需搭配EC02或EC03。'},
{code:'EC05',name:'輪椅附加功能-B款（仰躺）',price:2000,rent:150,unit:'月/購置',img:'wheelchair_recline',desc:'具椅背仰躺功能，配胸帶及防傾桿。',note:'需搭配EC02或EC03。'},
{code:'EC06',name:'輪椅附加功能-C款（空中傾倒）',price:4000,rent:150,unit:'月/購置',img:'wheelchair_tilt',desc:'座面空中傾倒功能，配胸帶及防傾桿。',note:'需搭配EC02或EC03。'},
{code:'EC07',name:'擺位系統-A款（平面型背靠）',price:1000,unit:'購置',img:'back_support',desc:'平面型輪椅背靠。',note:'EC07與EC08僅能擇一。'},
{code:'EC08',name:'擺位系統-B款（曲面適形背靠）',price:6000,unit:'購置',img:'back_support',desc:'曲面適形輪椅背靠。',note:'需輔具評估；免部分負擔。'},
{code:'EC09',name:'擺位系統-C款（軀幹側支撐架）',price:3000,unit:'購置',img:'back_support',desc:'輪椅軀幹側支撐架。',note:'申請單支者補助金額減半。'},
{code:'EC10',name:'擺位系統-D款（頭靠系統）',price:2500,unit:'購置',img:'headrest',desc:'可調整支撐高度、前後位置及角度之頭靠。',note:'需符合輪椅使用需求。'},
{code:'EC11',name:'電動輪椅',rent:2500,unit:'租賃/月',img:'power_wheelchair',desc:'電動輪椅租賃。',note:'與電動代步車僅能擇一。'},
{code:'EC12',name:'電動代步車',rent:1200,unit:'租賃/月',img:'scooter',desc:'四輪規格為原則之電動代步車。',note:'與電動輪椅僅能擇一。'},
{code:'ED01',name:'移位腰帶',price:1500,unit:'購置',img:'transfer_belt',desc:'協助抓握與安全移位。',note:'需輔具評估。'},
{code:'ED02',name:'移位板',price:2000,unit:'購置',img:'transfer_board',desc:'坐姿移位時作為相鄰平面橋板。',note:'最低使用年限5年。'},
{code:'ED03',name:'人力移位吊帶',price:4000,unit:'購置',img:'sling',desc:'坐姿或臥姿下以人力搬運移位。',note:'至少四個提把。'},
{code:'ED04',name:'移位滑墊-A款',price:3000,unit:'購置',img:'slide_sheet',desc:'坐姿下平行位移用。',note:'最低使用年限5年。'},
{code:'ED05',name:'移位滑墊-B款',price:8000,unit:'購置',img:'slide_sheet',desc:'臥姿下平行位移用。',note:'最低使用年限5年。'},
{code:'ED06',name:'移位轉盤',price:2000,unit:'購置',img:'turn_table',desc:'站立轉位輔助。',note:'上下接觸面需防滑。'},
{code:'ED07',name:'移位機',price:40000,rent:2000,unit:'月/購置',img:'hoist',desc:'懸吊式電動移位設備，應包含吊帶。',note:'可租賃可購置；需輔具評估。'},
{code:'ED08',name:'移位機吊帶',price:6000,unit:'購置',img:'sling',desc:'ED07購置三年後吊帶更換。',note:'限購置。'},
{code:'EE01',name:'電話擴音器',price:2000,unit:'購置',img:'phone_amp',desc:'協助聽覺受限者使用電話。',note:'最低使用年限5年。'},
{code:'EE02',name:'電話閃光震動器',price:2000,unit:'購置',img:'alert',desc:'電話來電閃光或震動提醒。',note:'最低使用年限5年。'},
{code:'EE03',name:'火警閃光警示器',price:2000,unit:'購置',img:'alert',desc:'火警閃光警示。',note:'最低使用年限5年。'},
{code:'EE04',name:'門鈴閃光器',price:2000,unit:'購置',img:'doorbell',desc:'門鈴閃光提示。',note:'最低使用年限5年。'},
{code:'EE05',name:'無線震動警示器',price:2000,unit:'購置',img:'alert',desc:'無線震動警示提醒。',note:'最低使用年限5年。'},
{code:'EF01',name:'衣著用輔具',price:500,unit:'購置',img:'dressing_aid',desc:'穿衣桿、穿鞋器、襪輔助器、長柄取物鉗等。',note:'最低使用年限3年。'},
{code:'EF02',name:'居家用生活輔具',price:500,unit:'購置',img:'daily_aid',desc:'特殊門把、開瓶罐器、特製開關、備藥提醒等。',note:'最低使用年限3年。'},
{code:'EF03',name:'飲食用輔具',price:500,unit:'購置',img:'eating_aid',desc:'特殊餐具、杯盤、防滑墊等。',note:'最低使用年限3年。'},
{code:'EG01',name:'氣墊床-A款',price:8000,rent:300,unit:'月/購置',img:'air_mattress',desc:'18管以上交替充氣氣墊床。',note:'免部分負擔；需輔具評估。'},
{code:'EG02',name:'氣墊床-B款',price:12000,rent:500,unit:'月/購置',img:'air_mattress',desc:'較高規格交替充氣氣墊床。',note:'免部分負擔；需輔具評估。'},
{code:'EG03',name:'輪椅座墊-A款（塑膠氣囊）',price:5000,unit:'購置',img:'cushion',desc:'連通管型氣囊氣墊座。',note:'免部分負擔。'},
{code:'EG04',name:'輪椅座墊-B款（橡膠氣囊）',price:10000,unit:'購置',img:'cushion',desc:'連通管型氣囊氣墊座。',note:'免部分負擔。'},
{code:'EG05',name:'輪椅座墊-C款（液態凝膠）',price:10000,unit:'購置',img:'cushion',desc:'液態凝膠座墊。',note:'免部分負擔。'},
{code:'EG06',name:'輪椅座墊-D款（固態凝膠）',price:8000,unit:'購置',img:'cushion',desc:'固態凝膠座墊。',note:'免部分負擔。'},
{code:'EG07',name:'輪椅座墊-E款（填充式氣囊）',price:8000,unit:'購置',img:'cushion',desc:'填充式氣囊氣墊座。',note:'免部分負擔。'},
{code:'EG08',name:'輪椅座墊-F款（交替充氣）',price:5000,unit:'購置',img:'cushion',desc:'交替充氣型座墊。',note:'免部分負擔。'},
{code:'EG09',name:'輪椅座墊-G款（量製型）',price:10000,unit:'購置',img:'cushion',desc:'依個別需求取模製作座墊。',note:'免部分負擔。'},
{code:'EH01',name:'居家用照顧床',price:8000,rent:1000,unit:'月/購置',img:'care_bed',desc:'三片以上床面，具頭部及腿靠床片升降功能。',note:'可租賃可購置；需輔具評估。'},
{code:'EH02',name:'居家用照顧床附加功能A（床面升降）',price:5000,rent:200,unit:'月/購置',img:'care_bed_lift',desc:'床面具升降功能。',note:'應搭配EH01同時申請。'},
{code:'EH03',name:'居家用照顧床附加功能B（電動升降）',price:5000,rent:500,unit:'月/購置',img:'care_bed_lift',desc:'具電動調整升降功能。',note:'應搭配EH01同時申請。'},
{code:'EH04',name:'爬梯機（單趟）',rent:700,unit:'租賃/趟',img:'stair_climber',desc:'按趟計費，上樓或下樓。',note:'需輔具評估；操作人員需受訓。'},
{code:'EH05',name:'爬梯機（月）',rent:4000,unit:'租賃/月',img:'stair_climber',desc:'按月租賃爬梯機。',note:'需輔具評估。'},
{code:'FA08',name:'反光貼條或消光處理',price:3000,unit:'購置',img:'anti_glare',desc:'樓梯、通路、浴室等地面反光貼條或消光處理。',note:'最低使用年限3年。'},
{code:'FA13',name:'水龍頭（單處）新增／改換',price:3000,unit:'購置',img:'faucet',desc:'改換撥桿式、單閥式或電子感應式水龍頭。',note:'最低使用年限10年。'},
{code:'FA15',name:'改善洗臉台（槽）',price:3000,unit:'購置',img:'sink',desc:'洗臉台新增、改換、移除含原處填補。',note:'未包含水龍頭。'},
{code:'FA17',name:'壁掛式淋浴台',price:5000,unit:'購置',img:'shower_seat_wall',desc:'固定於壁面作為淋浴支撐平台。',note:'最低使用年限10年。'},
{code:'FA18',name:'改善流理台',price:15000,unit:'購置',img:'kitchen',desc:'流理台新增或改換。',note:'須保留腿部淨空間。'},
{code:'FA19',name:'改善抽油煙機',price:1000,unit:'購置',img:'range_hood',desc:'抽油煙機高度或位置調整。',note:'最低使用年限10年。'},
{code:'FA22',name:'固定式扶手（每10公分）',price:160,unit:'10公分',img:'grab_bar',desc:'固定於牆面、天花板或地面之扶手。',note:'以握持部位每10公分為單位。'},
{code:'FA23',name:'可動式扶手',price:3600,unit:'支',img:'folding_bar',desc:'具可動關節並鎖固於牆面之扶手。',note:'最低使用年限10年。'},
{code:'FA24',name:'床邊扶手',price:1000,unit:'處',img:'bed_rail',desc:'置於床旁提供穩定支撐。',note:'最低使用年限10年。'},
{code:'FA25',name:'門檻斜角（單側）',price:1000,unit:'側',img:'threshold_ramp',desc:'改善10公分以下門檻高低落差。',note:'同一側與FA26-FA29擇一。'},
{code:'FA26',name:'非固定式斜坡板A款',price:3500,unit:'購置',img:'ramp',desc:'長度未達90公分，具攜帶功能。',note:'最低使用年限10年。'},
{code:'FA27',name:'非固定式斜坡板B款',price:5000,unit:'購置',img:'ramp',desc:'長度90公分以上未達120公分，可收折攜帶。',note:'最低使用年限10年。'},
{code:'FA28',name:'非固定式斜坡板C款',price:7000,unit:'購置',img:'ramp',desc:'長度120公分以上未達150公分，可收折攜帶。',note:'最低使用年限10年。'},
{code:'FA29',name:'非固定式斜坡板D款',price:10000,unit:'購置',img:'ramp',desc:'長度150公分以上，可收折攜帶。',note:'最低使用年限10年。'},
{code:'FA30',name:'改善高低差10公分以下',price:3500,unit:'處',img:'level_floor',desc:'門檻降低、順平、剔除或固定式斜坡道等。',note:'高度10公分以下。'},
{code:'FA31',name:'改善高低差20公分以下',price:5000,unit:'處',img:'level_floor',desc:'高低差逾10公分至20公分以下改善。',note:'最低使用年限10年。'},
{code:'FA32',name:'改善高低差30公分以下',price:7000,unit:'處',img:'level_floor',desc:'高低差逾20公分至30公分以下改善。',note:'最低使用年限10年。'},
{code:'FA33',name:'改善高低差超過30公分',price:10000,unit:'處',img:'level_floor',desc:'高低差逾30公分改善。',note:'最低使用年限10年。'},
{code:'FA34',name:'防滑地磚',price:6000,unit:'處',img:'anti_slip_tile',desc:'移除原地磚或整平後裝設防滑地磚。',note:'單處施作至少1平方公尺。'},
{code:'FA35',name:'防滑措施',price:2000,unit:'購置',img:'anti_slip_mat',desc:'防滑貼片、貼條、地墊、防滑劑等。',note:'最低使用年限3年。'},
{code:'FA36',name:'隔間（每平方公尺）',price:800,unit:'平方公尺',img:'partition',desc:'新增固定於地面之牆面。',note:'應扣除門面積。'},
{code:'FA37',name:'門簡易型',price:7000,unit:'處',img:'door',desc:'改變門片類型或增設門片含軌道。',note:'與FA38同一扇門僅能擇一。'},
{code:'FA38',name:'門進階型',price:10000,unit:'處',img:'door_wide',desc:'含門框施工之門加寬、加高、新增、調整位置等。',note:'與FA37同一扇門僅能擇一。'},
{code:'FA39',name:'截水槽',price:6000,unit:'處',img:'drain',desc:'施工長度須達60公分以上，含面蓋與施工費。',note:'最低使用年限10年。'},
{code:'FA40',name:'改善浴缸',price:7000,unit:'處',img:'bathtub',desc:'新增／改換開門式浴缸或拆除浴缸。',note:'最低使用年限10年。'},
{code:'FA41',name:'改善馬桶',price:5000,unit:'處',img:'toilet',desc:'馬桶新增、改換、移除、蹲式改坐式、加裝免治馬桶等。',note:'僅更換免治馬桶座蓋不補助。'},
{code:'FA42',name:'馬桶背靠',price:2000,unit:'處',img:'toilet_back',desc:'鎖固於牆面並具支撐面積之馬桶背靠。',note:'最低使用年限10年。'},
{code:'FA43',name:'移動式身體清洗槽－局部型',price:2000,unit:'購置',img:'wash_basin',desc:'內建排水裝置，深度15公分以上。',note:'最低使用年限3年。'},
{code:'FA44',name:'移動式身體清洗槽－全身型',price:5000,unit:'購置',img:'bath_bed',desc:'內建排水裝置，深度25公分以上且可包覆全身。',note:'最低使用年限3年。'},
{code:'EI01',name:'智慧科技輔具－移位類',rent:null,unit:'租賃',img:'smart_lift',desc:'移位裝置結合感測、紀錄、通報或省力機械功能。',note:'價格由特約單位訂定並報地方主管機關備查。'},
{code:'EI02',name:'智慧科技輔具－移動類',rent:null,unit:'租賃',img:'smart_mobility',desc:'電動輪椅、代步車或步行移動裝置結合監測或警示功能。',note:'價格由特約單位訂定並報備。'},
{code:'EI03',name:'智慧科技輔具－沐浴排泄類',rent:null,unit:'租賃',img:'smart_bath',desc:'協助沐浴或排泄處理，具監控、警示或照顧安全功能。',note:'價格由特約單位訂定並報備。'},
{code:'EI04',name:'智慧科技輔具－居家照顧床類',rent:null,unit:'租賃',img:'smart_bed',desc:'照顧床、床墊或感應墊具離床、翻身、久臥等警示功能。',note:'價格由特約單位訂定並報備。'},
{code:'EI05',name:'智慧科技輔具－安全看視類',rent:null,unit:'租賃',img:'smart_monitor',desc:'穿戴式、感應式或室內建置式設備，提供監測、安全防護與警示。',note:'不補助手機、手錶或一般日常生活用品。'}
].map(x=>({...x, category:x.code.startsWith('F')?'F居家無障礙':x.code.startsWith('EI')?'EI智慧科技輔具':'E輔具', type:'assistive', plain:x.desc}));

const allCodes = services.concat(assistiveServices);
const feeSelectable = allCodes.filter(x=>x.price || x.rent || x.code==='DA01');
